"""3일차 · 2교시 — 수익률·이동평균·lag"""
from kpc_course.dsl import *

UNIT = unit('stock-features', '3일차 · 2교시 — 수익률·이동평균·lag', [
    concept('lag-target', '과거 특성과 미래 정답을 구분하기',
        body='`pct_change`()는 이전 종가 대비 변화율입니다. `rolling`(5).`mean`()은 현재를 포함한 최근 5거래일 평균으로, 처음 4행에서는 값이 부족합니다. `shift`(1)은 이전 행의 값을 현재 행으로 가져오므로 `lag` 특성이 됩니다. `shift`(-1)은 다음 행을 가져와 다음 거래일 정답을 만듭니다.\n\n오늘 `Close`, `return_1`, `ma5`, `lag_close_1`을 입력으로 사용할 수 있습니다. `target_next_close`는 정답이며 입력에 넣지 않습니다. `target_date`도 정답이 실제로 발생하는 날짜를 확인할 용도로 유지합니다.\n\n이 파일은 401행에서 5거래일 평균의 첫 4행과 마지막 미래 정답 미상 한 행을 제외하면 396행이 남습니다. 날짜 인덱스와 `Target` 날짜를 같이 확인하세요. 숫자만 맞아 보여도 하루 밀린 정답이면 다른 문제를 푼 것입니다.',
        check=short('이전 거래일 값을 현재 행으로 가져오는 표현은?', ['shift(1)', '.shift(1)'], '양수 `shift`는 이전 행의 값을 가져옵니다.')),
    coding('daily-return', '하루 수익률 계산',
        goal="`prices['Close'].pct_change()`를 `return_1` 열로 추가하세요. 첫 행은 비어 있고(이전 값 없음), 둘째 행은 (53900 − 54100) / 54100 ≈ −0.0037입니다. `prices.head()`로 확인하세요.",
        hint="`pct_change()`는 (현재 − 이전) / 이전을 행마다 계산합니다. 새 열은 `prices['return_1'] = ...`처럼 대괄호에 새 이름을 적어 추가합니다.",
        starter="import pandas as pd\nprices = pd.read_csv('data/stock.csv', parse_dates=['Date']).set_index('Date').sort_index()\n# return_1 열을 만들고 head()를 확인하세요\n",
        solution="import pandas as pd\nprices = pd.read_csv('data/stock.csv', parse_dates=['Date']).set_index('Date').sort_index()\nprices['return_1'] = prices['Close'].pct_change()\nprices.head()\n",
        check="import pandas as pd\nassert pd.isna(s['prices']['return_1'].iloc[0])\nassert abs(s['prices']['return_1'].iloc[1]-(53900/54100-1))<1e-12"),
    coding('moving-average', '5거래일 이동평균',
        goal="`prices['Close'].rolling(5).mean()`을 `ma5` 열로 추가하세요. 처음 4행은 값이 부족해 비어 있고, 다섯째 행은 첫 5개 종가의 평균 53940입니다. `prices.head(6)`으로 확인하세요.",
        hint='`rolling(5)`는 현재 행을 포함한 최근 5행 창을 만들고 `.mean()`이 그 평균을 구합니다. 5개가 안 모인 처음 4행은 `NaN`입니다.',
        starter="import pandas as pd\nprices = pd.read_csv('data/stock.csv', parse_dates=['Date']).set_index('Date').sort_index()\n# ma5 열을 만들고 head(6)을 확인하세요\n",
        solution="import pandas as pd\nprices = pd.read_csv('data/stock.csv', parse_dates=['Date']).set_index('Date').sort_index()\nprices['ma5'] = prices['Close'].rolling(5).mean()\nprices.head(6)\n",
        check="assert s['prices']['ma5'].iloc[:4].isna().all()\nassert s['prices']['ma5'].iloc[4]==53940\nassert s['prices']['ma5'].isna().sum()==4"),
    coding('lag-next', '과거와 미래 열 만들기',
        goal='`prices`에 `lag_close_1`은 `Close.shift`(1), `target_next_close`는 `Close.shift`(-1)로 추가하세요. 첫 행의 과거값과 마지막 행의 미래값은 비어 있어야 합니다.',
        hint="`prices['Close'].shift(1)`은 이전 거래일 값을 현재 행에 놓습니다. `.shift(-1)`은 다음 거래일 값을 현재 행에 놓으므로 예측할 정답을 만들 때 사용합니다.",
        starter="import pandas as pd\nprices = pd.read_csv('data/stock.csv', parse_dates=['Date']).set_index('Date').sort_index()\n# 두 열을 만드세요\n",
        solution="import pandas as pd\nprices = pd.read_csv('data/stock.csv', parse_dates=['Date']).set_index('Date').sort_index()\nprices['lag_close_1']=prices['Close'].shift(1)\nprices['target_next_close']=prices['Close'].shift(-1)\nprices.head()\n",
        check="assert __import__('pandas').isna(s['prices']['lag_close_1'].iloc[0])\nassert s['prices']['lag_close_1'].iloc[1]==54100\nassert s['prices']['target_next_close'].iloc[0]==53900\nassert __import__('pandas').isna(s['prices']['target_next_close'].iloc[-1])"),
    coding('stock-frame', '미래 정답을 포함한 분석 표',
        goal='`frame`에 `close`, `return_1`, `ma5`, `lag_close_1`, `target_next_close`, `target_date`를 만드세요. `return_1`은 `pct_change`, `ma5`는 `rolling`(5).`mean`입니다. `target_date`는 날짜 인덱스를 `Series`로 만든 뒤 `shift`(-1)합니다. 마지막에 `dropna`로 불완전한 행을 제외하세요.',
        hint='현재 종가, `.pct_change()` 수익률, `.rolling(5).mean()` 이동평균, `.shift(1)` 전일 종가를 입력 열로 만드세요. 다음 종가와 날짜는 `.shift(-1)`로 만들고 마지막에 `.dropna().copy()`로 불완전한 행을 제외합니다.',
        starter="import pandas as pd\nprices = pd.read_csv('data/stock.csv', parse_dates=['Date']).set_index('Date').sort_index()\nframe=pd.DataFrame(index=prices.index)\n# 여섯 열을 만들고 불완전한 행을 제외하세요\n",
        solution="import pandas as pd\nprices = pd.read_csv('data/stock.csv', parse_dates=['Date']).set_index('Date').sort_index()\nframe=pd.DataFrame(index=prices.index)\nframe['close']=prices['Close']\nframe['return_1']=prices['Close'].pct_change()\nframe['ma5']=prices['Close'].rolling(5).mean()\nframe['lag_close_1']=prices['Close'].shift(1)\nframe['target_next_close']=prices['Close'].shift(-1)\nframe['target_date']=pd.Series(prices.index,index=prices.index).shift(-1)\nframe=frame.dropna().copy()\nprint(frame.shape)\nframe.head()\n",
        check="assert s['frame'].shape==(396,6)\nassert s['frame'].notna().all().all()\nassert (s['frame']['target_date']>s['frame'].index).all()\nassert s['frame']['ma5'].iloc[0]==s['prices']['Close'].iloc[:5].mean()"),
    quiz('feature-time-check', '시점과 특성',
        short('다음 거래일 값을 가져오는 `shift` 인자는?', ['-1'], '`shift`(-1)은 다음 행을 현재 행으로 옮깁니다.'),
        choice('`target_next_close`를 `X`에도 넣으면?', ['미래 정보 누수', '정상적인 과거 특성'], 0, '예측할 정답이 입력에 섞입니다.'),
        short('5거래일 평균에서 처음 비는 행 수는?', ['4'], '첫 4행은 5개 관측값이 아직 없습니다.'),
        choice('`pct_change()`의 첫 행이 `NaN`인 이유는?', ['비교할 이전 거래일이 없음', '계산 오류'], 0, '첫 행에는 이전 값이 없어 변화율을 계산할 수 없습니다.'),
        short('최근 5행 평균을 구하는 표현은? (`Close.________(5).mean()`)', ['rolling', 'rolling(5)'], '`rolling(5)`는 5행 이동 창을 만듭니다.'),
    ),
])
