"""해설 모드 scripts for the credit chapter (부도 정의, 네 지표 + ★ 도전 과제): what the tutor says
and types for each concept and coding problem, keyed by activity id. Format and rules: narration.py.

Voice: the instructor's (see .scratch/presenter-decks/spec.md): 해요체 구어, "자," opens a scene,
one or two short sentences per line, says what the student should look at right now. The course's
words stay as they are: 입력 X, 정답 y, 훈련 자료/테스트 자료, 기준 모델, 누수, 정밀도, 재현율, 기준값.
"""

NARRATION = {
    # ---- 부도 정의와 연체 이력 ----
    "credit-definition": [
        ("title", "자, 타이타닉에서 익힌 분류를 이번엔 돈 문제에 써요. 제목부터 보세요. 지난달 연체와 다음 달 부도는 다른 칸이에요."),
        ("타이타닉으로 분류의 흐름을 익혔으니 금융 자료에 옮겨 봅니다", "credit.csv는 카드 고객 3만 명, 한 사람이 한 행이에요. 맞힐 칸은 다음달 부도, 1이면 부도 0이면 정상이에요. 열 이름에 공백이 있어서 target 변수에 담아 credit[target]으로 꺼내요."),
        ("제목: 아는 것과 맞힐 것", "만화를 보세요. 지난달 연체 기록은 지금 아는 과거라 입력에 넣어도 돼요. 맞힐 건 다음 달 부도, 그 칸만 정답 y예요."),
        ("입력 열은 타이타닉보다 많습니다", "입력 열이 꽤 많아요. 성별, 학력, 결혼은 숫자 코드인데 크기가 아니에요. 성별 2가 1보다 큰 게 아니죠? 고객번호는 사람 구별용 번호라 입력에서 빼요."),
        ("가장 중요한 열은 상환 상태", "가장 중요한 건 상환 상태 여섯 열이에요. 상환_9월이 가장 최근 달이고, 번호가 작아질수록 더 전 달이에요."),
        ("쓴 돈이 없음", "값의 뜻은 이 표예요. 마이너스는 쓴 돈이 없거나 제때 다 갚은 거고, 0은 최소 금액만 낸 거예요. 1부터는 그 달수만큼 연체한 거죠."),
        ("여기서 선을 하나 긋습니다", "여기서 선을 하나 그어요. 상환_9월은 지난달까지의 기록, target은 다음 달 결과예요. 시점이 다르니까 상환_9월은 입력에 넣어도 누수가 아니에요."),
        ("제목: 지난달과 다음 달", "만화에서 준호가 헷갈리죠? 지난달 연체는 이미 아는 기록이고, 맞히려는 건 다음 달 결과예요. 과거 기록으로 미래를 맞히는 게 이 문제예요."),
        ("credit[target].value_counts()", "코드는 전부 아는 거예요. value_counts로 부도와 정상 인원, groupby로 상환 상태별 인원과 부도율. 자료만 바뀌었고 몇 명 중인지 같이 보는 습관도 그대로예요."),
        ("check", "확인 문항이요. 타깃 다음달 부도에서 부도를 나타내는 값, 방금 봤죠?"),
    ],
    "credit-shape": [
        ("problem", "자, 새 자료는 뼈대부터 봐요. credit의 행 수와 열 수를 n_rows, n_columns에 담고, 타깃의 value_counts를 target_counts에 담아 둘 다 출력하면 돼요."),
        ("starter", "준비 코드가 credit.csv를 읽고 target에 열 이름을 담아 뒀어요. 그대로 둘게요."),
        ("code", "n_rows, n_columns = credit.shape\n", "shape는 행 수, 열 수 두 개를 돌려주니까 이름 두 개에 나눠 담아요."),
        ("code", "target_counts = credit[target].value_counts()\n", "열 이름에 공백이 있어서 점으로는 못 불러요. credit[target]으로 꺼내서 value_counts를 세요."),
        ("code", "print(n_rows, n_columns)\nprint(target_counts)\n", "두 줄로 출력해요. 크기 먼저, 인원 표 다음이요."),
        ("output", "30000 25가 나왔죠? 3만 명에 25열이에요. 아래 표를 보면 정상 0이 23364명, 부도 1이 6636명. 정상이 훨씬 많아요."),
        ("submit", "제출할게요. 검사는 행 수, 열 수와 두 인원을 봐요."),
    ],
    "default-summary": [
        ("problem", "자, 부도 인원과 부도율을 구하고 입력 표 X를 만들어요. 타깃이 0과 1이라 합이 인원, 평균이 부도율이에요. X에서는 고객번호와 정답 열을 빼면 돼요."),
        ("starter", "준비 코드는 그대로 두고 아래에 이어 써요."),
        ("code", "default_count=int(credit[target].sum())\ndefault_rate=credit[target].mean()\n", "1만 더해지니까 sum이 부도 인원이에요. int로 감싸서 정수로 두고요. mean은 0과 1의 평균이라 그게 바로 부도율이에요."),
        ("code", "X=credit.drop(columns=['고객번호',target])\n", "drop에 뺄 열 두 개를 리스트로 넘겨요. 고객번호는 사람 구별용이라 규칙의 재료가 아니고, target은 정답이니까 입력에 있으면 안 되죠."),
        ("code", "print(default_count,f'{default_rate:.2%}',X.shape)\n", "출력할 때 .2%를 붙이면 소수 둘째 자리 퍼센트로 보여 줘요."),
        ("output", "6636 22.12% (30000, 23)이 나왔어요. 부도율 22%쯤, X는 25열에서 둘 빠져 23열이에요."),
        ("submit", "제출할게요."),
    ],
    "limit-by-default": [
        ("problem", "자, 타이타닉에서 쓴 groupby를 그대로 가져와요. 타깃으로 묶어서 신용한도의 평균을 구해 limit_by_default에 담고 출력하면 돼요."),
        ("starter", "준비 코드는 그대로 둘게요."),
        ("code", "limit_by_default = credit.groupby(target)['신용한도'].mean()\n", "groupby 괄호에 묶는 열 target, 대괄호에 평균 낼 열 신용한도. 타이타닉에서 성별로 묶어 생존 평균 낸 것과 같은 모양이에요."),
        ("code", "print(limit_by_default)\n", "출력해서 두 그룹을 비교해요."),
        ("output", "정상 0은 약 17만 8천, 부도 1은 약 13만. 한도가 낮은 쪽에 부도가 더 많아요. 다만 원인이라고 단정하진 말아요. 관찰이에요."),
        ("submit", "제출할게요."),
    ],
    "delay-groups": [
        ("problem", "자, 여섯 달 중 한 번이라도 연체한 적이 있는지를 새 열 has_delay로 만들어요. 그걸로 묶어 타깃의 count, sum, mean을 summary에 담으면 돼요."),
        ("starter", "준비 코드에 pay_columns가 있어요. 상환_9월부터 상환_4월까지 여섯 열 이름이에요. 그대로 둘게요."),
        ("code", "credit['has_delay']=(credit[pay_columns]>=1).any(axis=1)\n", "credit[pay_columns] >= 1은 여섯 열 전부에 참, 거짓을 매긴 표예요. any(axis=1)은 행마다 하나라도 참이면 참. 그걸 새 열에 넣어요."),
        ("code", "summary=credit.groupby('has_delay')[target].agg(['count','sum','mean'])\n", "has_delay로 묶고 agg에 세 개를 한 번에 넘겨요. 몇 명 중 몇 명이 부도고 비율은 얼마인지 한 표에 나오거든요."),
        ("code", "summary\n", "마지막 줄에 summary만 적으면 표로 보여 줘요."),
        ("output", "표를 보세요. 연체 경험 없는 쪽은 19931명 중 부도율 약 11.7%, 있는 쪽은 10069명 중 약 42.7%예요. 네 배 가까이 차이 나죠?"),
        ("submit", "제출할게요."),
    ],
    "pay0-rate": [
        ("problem", "자, 가장 최근 달 상환_9월로 묶어서 타깃의 count와 mean을 pay0_summary에 담아요. 그중 상태 0의 부도율을 rate_0, 상태 2의 부도율을 rate_2에 담아 출력하면 돼요."),
        ("starter", "준비 코드는 그대로 둘게요."),
        ("code", "pay0_summary = credit.groupby('상환_9월')[target].agg(['count','mean'])\n", "개념에서 본 그 줄이에요. 상환_9월로 묶고 count와 mean을 같이 봐요. 비율만 보면 속으니까 인원을 꼭 붙여요."),
        ("code", "rate_0 = pay0_summary.loc[0,'mean']\nrate_2 = pay0_summary.loc[2,'mean']\n", "표에서 한 칸을 꺼낼 땐 loc에 행 이름, 열 이름이에요. 상태 0의 mean, 상태 2의 mean이죠."),
        ("code", "print(pay0_summary)\nprint(rate_0, rate_2)\n", "표를 먼저, 두 비율을 그다음에 출력해요."),
        ("output", "rate_0은 약 0.128, rate_2는 약 0.691이에요. 2개월 연체면 부도율이 다섯 배가 넘죠? 그런데 상태 7은 78%인데 9명뿐이에요. 분모가 작은 비율은 믿지 말아요."),
        ("submit", "제출할게요."),
    ],

    # ---- 네 지표와 확률 기준 ----
    "manual-metrics": [
        ("problem", "자, 이 단원은 개념 없이 문제 안에서 설명해요. 부도율이 22%니까 전원 정상이라고 찍어도 정확도 78%예요. 그래서 맞힘과 틀림을 네 칸으로 나눠요. 그게 혼동행렬이에요. 위 설명과 만화를 읽고, 작은 숫자로 정밀도, 재현율, 정확도를 손으로 계산해요."),
        ("hint", "정밀도 분모는 부도라고 경고한 수 tp 더하기 fp, 재현율 분모는 진짜 부도 수 tp 더하기 fn이에요. 만화에서 보낸 경고 중 맞은 비율, 진짜 부도 중 잡은 비율, 그거예요."),
        ("starter", "준비 코드에 tp, fp, fn, tn이 2, 1, 1, 2로 있어요. 그대로 둘게요."),
        ("code", "precision = tp / (tp + fp)\n", "정밀도는 부도라고 경고한 사람 중 진짜 부도였던 비율이에요. 경고의 신뢰도죠. tp를 tp 더하기 fp로 나눠요."),
        ("code", "recall = tp / (tp + fn)\n", "재현율은 진짜 부도 중 미리 찾아낸 비율이에요. 놓치지 않은 정도죠. 분모가 tp 더하기 fn으로 바뀌는 게 전부예요."),
        ("code", "accuracy = (tp + tn) / (tp + fp + fn + tn)\n", "정확도는 전체 중 맞힌 비율이에요. 맞힌 두 칸 tp와 tn을 네 칸 합으로 나눠요."),
        ("code", "print(precision, recall, accuracy)\n", "세 값을 한 줄에 출력해요."),
        ("output", "셋 다 0.6666이 나왔죠? 숫자가 작아서 같아졌어요. 공식이 손에 익었으면 다음 미션에선 함수로 해요."),
        ("submit", "제출할게요."),
    ],
    "metrics-matrix": [
        ("problem", "자, 같은 계산을 scikit-learn 함수로 해요. 정답 y_true와 예측 y_pred 여섯 개로 네 지표를 metrics 딕셔너리에 담고, 혼동행렬을 matrix에 담아 둘 다 출력하면 돼요."),
        ("starter", "준비 코드가 함수 다섯 개를 불러오고 y_true, y_pred를 만들어 뒀어요. 그대로 둘게요."),
        ("code", "metrics={'accuracy':accuracy_score(y_true,y_pred),'precision':precision_score(y_true,y_pred),'recall':recall_score(y_true,y_pred),'f1':f1_score(y_true,y_pred)}\n", "지표 함수는 전부 정답, 예측 순서로 넣어요. 네 개를 같은 이름의 키로 딕셔너리에 담아요. 순서를 바꾸면 정밀도와 재현율이 뒤바뀌거든요."),
        ("code", "matrix=confusion_matrix(y_true,y_pred,labels=[0,1])\n", "혼동행렬도 정답, 예측 순서예요. labels를 0, 1로 주면 행과 열 순서가 고정돼요. 왼쪽 위가 TN, 오른쪽 아래가 TP예요."),
        ("code", "print(metrics)\nprint(matrix)\n", "딕셔너리와 행렬을 차례로 출력해요."),
        ("output", "네 지표가 전부 0.6666이고, 행렬이 2 1, 1 2죠? TN 2, FP 1, FN 1, TP 2. 앞 미션과 같은 상황이에요."),
        ("submit", "제출할게요."),
    ],
    "credit-model": [
        ("problem", "자, 진짜 자료예요. 준비 코드가 상환_9월, 신용한도, 나이 세 열로 훈련 자료와 테스트 자료를 나눠 뒀어요. 기준 모델 Dummy와 Logistic을 각각 StandardScaler와 묶은 Pipeline으로 학습해서 네 지표를 results 표로 만들면 돼요."),
        ("hint", "앞 단원의 표 만들기 패턴 그대로예요. 정밀도, 재현율, F1에 zero_division=0을 주면 기준 모델처럼 TP가 0일 때 경고 없이 0이 나와요."),
        ("starter", "준비 코드는 불러오기, 입력 X, 정답 y, 그리고 train_test_split이에요. 그대로 둘게요."),
        ("code", "models={'Dummy':DummyClassifier(strategy='most_frequent'),'Logistic':LogisticRegression(max_iter=2000)}\nrows=[]\n", "모델 두 개를 딕셔너리에 담아요. Dummy는 가장 많은 답, 그러니까 전원 정상으로 찍는 기준 모델이에요. 결과 행을 모을 빈 리스트 rows도 만들고요."),
        ("code", "for name,estimator in models.items():\n    model=Pipeline([('scale',StandardScaler()),('model',estimator)])\n    model.fit(X_train,y_train)\n    pred=model.predict(X_test)\n", "모델마다 돌면서 StandardScaler와 묶은 Pipeline을 만들어요. fit은 훈련 자료로만, predict는 테스트 자료로. 이 순서가 누수를 막아요."),
        ("code", "    rows.append({'model':name,'accuracy':accuracy_score(y_test,pred),'precision':precision_score(y_test,pred,zero_division=0),'recall':recall_score(y_test,pred,zero_division=0),'f1':f1_score(y_test,pred,zero_division=0)})\n", "네 지표를 딕셔너리 한 줄로 rows에 붙여요. 정답 y_test, 예측 pred 순서고요. zero_division=0은 TP가 0일 때 경고 대신 0을 적으라는 뜻이에요."),
        ("code", "results=pd.DataFrame(rows).set_index('model')\nresults\n", "rows를 DataFrame으로 만들고 model 열을 행 이름으로 세워요. 마지막 줄에 results만 적으면 표로 떠요."),
        ("output", "표를 보세요. Dummy는 정확도 0.779인데 정밀도, 재현율, F1이 전부 0이에요. 부도를 한 명도 못 찾은 거죠. Logistic은 정확도 0.810, 재현율 0.258, 정밀도 0.691이에요. 정확도는 조금 오르고 재현율은 0에서 26%로 올라왔어요."),
        ("submit", "제출할게요."),
    ],
    "predict-proba": [
        ("problem", "자, 로지스틱 회귀는 사실 부도일 확률을 먼저 계산하고 0.5를 넘으면 부도라고 답해요. 위 위젯에서 기준값을 움직여 보세요. 학습된 model에서 부도 확률을 probabilities에 담고, 0.5 이상인 고객 수와 0.3 이상인 고객 수를 세어 출력하면 돼요."),
        ("starter", "준비 코드가 Pipeline으로 Logistic을 학습까지 해 뒀어요. 그대로 둘게요."),
        ("code", "probabilities = model.predict_proba(X_test)[:, 1]\n", "predict_proba는 행마다 정상 확률, 부도 확률 두 열을 돌려줘요. 콜론 쉼표 1로 두 번째 열, 부도 확률만 골라요."),
        ("code", "n_positive_05 = int((probabilities >= 0.5).sum())\nn_positive_03 = int((probabilities >= 0.3).sum())\n", "probabilities >= 0.5는 참, 거짓 배열이고 sum이 참의 개수예요. 같은 식에서 기준값만 0.3으로 바꾸고, 둘 다 int로 감싸 정수로 둬요."),
        ("code", "print(n_positive_05, n_positive_03)\n", "두 개수를 나란히 출력해요."),
        ("output", "495 1155가 나왔죠? 기준을 0.5에서 0.3으로 낮추니 부도 경고가 495명에서 1155명으로, 두 배 넘게 늘었어요. 모델은 그대로고 기준만 바꾼 거예요."),
        ("submit", "제출할게요."),
    ],
    "thresholds": [
        ("problem", "자, 확률을 0과 1로 바꾸는 규칙을 손으로 써 봐요. 만화를 보세요. 35%인 고객에게 경고를 보낼지는 모델이 아니라 사람이 정하거든요. 확률 다섯 개로 0.5 기준 pred_05, 0.3 기준 pred_03을 만들고 1의 개수를 출력하면 돼요."),
        ("starter", "준비 코드에 확률 다섯 개가 numpy 배열로 있어요. 0.1, 0.35, 0.49, 0.51, 0.8. 그대로 둘게요."),
        ("code", "pred_05=(probabilities>=0.5).astype(int)\n", "probabilities >= 0.5는 참, 거짓 배열이에요. astype(int)를 붙이면 참이 1, 거짓이 0이 돼요. 그게 바로 예측이에요."),
        ("code", "pred_03=(probabilities>=0.3).astype(int)\n", "같은 식에서 기준값만 0.3으로 바꿔요. 0.35와 0.49가 이제 1로 넘어오죠."),
        ("code", "print(pred_05.sum(),pred_03.sum())\n", "1의 개수는 sum이에요. 두 기준의 개수를 나란히 출력해요."),
        ("output", "2 4가 나왔죠? 같은 확률인데 기준을 낮추니 경고가 둘에서 넷으로 늘었어요. 놓치는 부도 FN은 줄고 멀쩡한 고객 경고 FP는 늘어요. 그 기준값은 비용을 아는 사람이 정해요."),
        ("submit", "제출할게요."),
    ],

    # ---- ★ 도전 과제 — 임계값과 비용 ----
    "threshold-cost": [
        ("problem", "자, 도전 과제예요. 은행은 지표가 아니라 돈으로 정해요. 부도를 놓치면 100만 원, 멀쩡한 고객에게 경고하면 5만 원이에요. 확률, 기준값, 혼동 행렬을 다 써서 기준값 0.5와 0.3의 비용을 비교하면 돼요."),
        ("hint", "혼동 행렬에서 FN은 1, 0 칸, FP는 0, 1 칸이에요. 비용은 FN 곱하기 100만 더하기 FP 곱하기 5만. 싼 쪽을 cheaper에 담아요."),
        ("starter", "준비 코드가 세 열로 훈련 자료와 테스트 자료를 나누고 Pipeline까지 학습해 뒀어요. 그대로 둘게요."),
        ("code", "probabilities = model.predict_proba(X_test)[:, 1]\n", "먼저 테스트 자료의 부도 확률이에요. predict_proba의 두 번째 열, 앞 미션 그대로예요."),
        ("code", "cm_05 = confusion_matrix(y_test, (probabilities >= 0.5).astype(int), labels=[0, 1])\ncm_03 = confusion_matrix(y_test, (probabilities >= 0.3).astype(int), labels=[0, 1])\n", "기준값마다 확률을 0과 1로 바꿔서 바로 confusion_matrix에 넣어요. 정답 y_test가 앞, 예측이 뒤. labels로 칸 위치를 고정해요."),
        ("code", "cost_05 = int(cm_05[1, 0]) * 1_000_000 + int(cm_05[0, 1]) * 50_000\ncost_03 = int(cm_03[1, 0]) * 1_000_000 + int(cm_03[0, 1]) * 50_000\n", "비용식이에요. 1, 0 칸이 놓친 부도 FN이라 100만 원씩, 0, 1 칸이 멀쩡한 고객 경고 FP라 5만 원씩. int로 감싸서 정수로 둬요."),
        ("code", "cheaper = 0.3 if cost_03 < cost_05 else 0.5\nprint(cost_05, cost_03, cheaper)\n", "두 비용을 비교해서 싼 쪽 기준값을 cheaper에 담고, 세 값을 출력해요."),
        ("output", "992650000 744250000 0.3이 나왔죠? 0.5면 약 9억 9천만 원, 0.3이면 약 7억 4천만 원이에요. 0.3으로 낮추면 경고 FP가 153에서 545로 늘지만 놓친 부도 FN이 985에서 717로 줄어서, 2억 5천만 원 가까이 싸요. 그래서 기준값은 비용을 아는 사람이 정하는 거예요."),
        ("submit", "제출할게요. 수업 전체를 다 쓴 미션이에요."),
    ],
    "rate-by-attribute": [
        ("problem", "자, 이번엔 고객 속성별 부도율이에요. 성별, 학력은 코드 그대로 묶고, 나이는 다섯 구간으로 잘라서 묶어요."),
        ("starter", "준비 코드는 credit 표와 target 이름이에요. 그대로 둘게요."),
        ("code", "rate_by_sex = credit.groupby('성별')[target].mean()\nrate_by_education = credit.groupby('학력')[target].mean()\n", "groupby로 묶고 타깃의 평균. 0과 1의 평균이 곧 부도율이죠? 성별로 한 번, 학력으로 한 번이에요."),
        ("code", "credit['나이대'] = pd.cut(credit['나이'], bins=[20, 30, 40, 50, 60, 80], right=False, labels=['20대', '30대', '40대', '50대', '60대 이상'])\n", "나이는 pd.cut으로 구간 열을 만들어요. right=False라 20 이상 30 미만이 20대예요. 타이타닉 나이 구간과 같은 방법이에요."),
        ("code", "rate_by_age = credit.groupby('나이대', observed=True)[target].mean()\nprint(rate_by_sex)\nprint(rate_by_education)\nprint(rate_by_age)\n", "구간 열로 묶어 평균을 내고 셋을 출력해요. observed=True는 빈 구간을 빼라는 뜻이에요."),
        ("output", "남성 24.2%, 여성 20.8%. 나이대는 30대가 20.3%로 가장 낮고 60대 이상이 28.3%예요. 차이가 있긴 한데, 앞 미션의 연체 이력 차이(11.7% 대 42.7%)에 비하면 작죠?"),
        ("submit", "제출할게요. 검사는 성별 인덱스, 나이대 다섯 구간, 남성과 60대 이상 비율을 봐요."),
    ],
}
