"""해설 모드 scripts for chapter 5 (modeling): what the tutor says and types for each concept and
coding problem of the three units (features, preprocessing, classifiers) and the chapter's challenge,
keyed by activity id. Format and rules: narration.py.

Voice: the instructor's (see .scratch/presenter-decks/spec.md): 해요체 구어, "자," opens a scene,
one or two short sentences per line, says what the student should look at right now. Uses the
course's words (입력 X, 정답 y, 훈련 자료/테스트 자료, 기준 모델, 누수, 하이퍼파라미터, 과적합) and its
analogies only (빵 공장, 콜센터, 문제집과 모의고사, 답만 외운 학생, 팀장의 감).

Code chunks copy the solution text character for character, including its spacing style
(`a=b` in the shared prep strings, `a = b` in the hand-written tails). Output lines state the
values the solution actually prints with data/titanic.csv.
"""

NARRATION = {
    # ---- 입력과 정답 분리 ----
    "what-is-learning": [
        ("title", "자, 여기서부터 머신러닝이에요. 하는 일은 하나, 표에서 규칙을 찾아 빈칸을 채우는 거예요."),
        ('지금까지 "누가 살아남았나"를 표와 그림으로', "지금까진 누가 살아남았나를 표로 들여다봤죠? 이제 질문을 바꿔요. 승객 정보만 보고 생존을 맞힐 수 있을까. 사람이 규칙을 적는 대신 컴퓨터가 1,309명 기록에서 규칙을 찾는 거예요."),
        ("제목: 아는 칸으로 모르는 칸을 채운다", "그림을 보세요. 왼쪽이 아는 것, 입력 X예요. 오른쪽이 맞힐 것, 정답 y죠. 위 세 줄은 답을 알고, 마지막 줄만 물음표예요."),
        ('위 세 행에서 "여성이면 살아남는 쪽', "위 세 줄에서 여성이면 살아남는 쪽, 3등실이면 죽는 쪽, 이런 규칙을 찾아요. 그 규칙으로 물음표를 채우면 그게 학습이고 예측이에요."),
        ("용어 네 개만 정리하면 됩니다", "단어 네 개만 잡아요. 재료 열이 입력 X, 맞힐 칸이 정답 y. 규칙 찾기가 fit, 적용이 predict예요. 생존이냐 사망이냐 고르면 분류, 주가처럼 숫자를 맞히면 회귀거든요."),
        ("그런데 규칙을 찾은 다음, 그 규칙이 쓸 만한지", "그런데 찾은 규칙이 쓸 만한지 어떻게 알까요? 배운 1,309명에게 다시 물으면 당연히 잘 맞혀요. 푼 문제집으로 시험 치는 셈이죠."),
        ("제목: 문제집과 모의고사", "만화를 보세요. 일부를 떼어 두고 다 배운 뒤 한 번만 채점해요. 훈련 자료가 문제집, 테스트 자료가 모의고사예요. 모의고사는 미리 보면 안 되죠?"),
        ("model.fit(X_train, y_train)", "코드 네 줄이 전부예요. 열로 갈라 X와 y, 행으로 갈라 훈련과 테스트. 훈련으로 fit하고 테스트로 predict해요."),
        ("이 흐름은 마지막 챕터까지 변하지 않습니다", "이 흐름은 마지막 챕터까지 안 바뀌어요. 남은 미션은 이 네 줄을 제대로 하기 위한 준비거든요."),
        ("check", "확인 문항이요. 다 배운 뒤 한 번만 채점하는 자료, 모의고사 쪽이요."),
    ],
    "leakage": [
        ("title", "자, 어느 열을 입력에 넣을지 정할 때 꼭 지켜야 할 원칙 하나예요."),
        ("입력으로 어떤 열을 쓸지 고를 때 앞 챕터의 원칙이 그대로 옵니다", "맞히려는 시점에 알 수 있는 것만. 등급, 성별, 나이는 배 타기 전에 정해지죠. 그런데 구명보트 번호와 시신번호는 사고가 끝난 뒤에 적혀요. 이걸 넣으면 거의 100%를 맞히는데, 쓸모가 없어요."),
        ("위젯: leakage", "위젯을 만져 보세요. 구명보트 열을 넣고 빼면서 점수가 어떻게 뛰는지 보시면 돼요. 점수가 높을수록 수상한 거예요."),
        ("제목: 시험지에 적힌 답", "만화의 준호처럼 100%가 나오면 기뻐할 게 아니라 물어야 해요. 이 값은 언제 적히나. 사고 전에는 모르는 값이면 그게 누수예요."),
        ("이렇게 정답을 알려 주는 정보가 입력에 새어 들어오는 것을 누수", "정답을 알려 주는 정보가 입력에 새어 들어오는 것, 이게 누수예요. 가장 노골적인 건 생존 열 자체를 넣는 거고, 구명보트처럼 사실상 정답인 열도 누수거든요. 누수가 있으면 점수가 아무리 높아도 못 믿어요."),
        ("사고 전에 알 수 있는 7개 열", "코드를 보세요. 사고 전에 알 수 있는 일곱 열만 features에 담아 X를 만들고, 생존을 정수로 바꿔 y로 둬요."),
        ("이름, 티켓 번호, 선실 번호, 목적지도 뺍니다", "이름, 티켓, 선실, 목적지도 빼요. 누수는 아니지만 사람마다 거의 다 달라서 규칙 재료가 못 되거든요. 남은 열에는 글자 열과 빈칸이 있어서 손질이 필요한데, 그건 다음 단원이에요."),
        ("check", "확인 문항이요. 답이 입력에 섞여 들어와 점수를 못 믿게 되는 현상, 방금 만화 제목이 힌트예요."),
    ],
    "drop-columns": [
        ("problem", "자, 입력 후보를 추려요. titanic에서 정답 생존과 쓰지 않을 열 여섯 개를 drop으로 빼서 candidates에 담고, 남은 열 이름을 출력하면 돼요. 일곱 열이 남으면 맞아요."),
        ("starter", "준비 코드가 titanic.csv를 읽어 뒀어요. 그대로 둘게요."),
        ("code", "candidates = titanic.drop(columns=['생존','이름','티켓','선실','구명보트','시신번호','출신목적지'])\n", "drop(columns=[...])에 뺄 열 이름을 리스트로 넣어요. 생존은 정답이라 빼고, 구명보트와 시신번호는 누수라 빼고, 이름과 티켓, 선실, 출신목적지는 규칙 재료가 못 돼서 빼는 거예요. 결과를 candidates에 받아요."),
        ("code", "print(list(candidates.columns))\n", "남은 열 이름을 리스트로 출력해요. columns를 list로 감싸면 보기 편하거든요."),
        ("output", "객실등급, 성별, 나이, 형제배우자, 부모자녀, 요금, 탑승항구. 일곱 열이 남았죠? 전부 사고 전에 알 수 있는 값이에요."),
        ("submit", "제출하면 열 일곱 개와 행 1309개가 맞는지 확인해요."),
    ],
    "xy-separation": [
        ("problem", "자, 이번엔 쓸 열을 직접 골라서 입력 X와 정답 y를 만들어요. 일곱 열 이름을 features 리스트에 담고, X는 그 열만 복사, y는 생존을 정수로 담으면 돼요."),
        ("starter", "준비 코드는 titanic을 읽는 두 줄이에요. 그대로 둘게요."),
        ("code", "features=['객실등급','성별','나이','형제배우자','부모자녀','요금','탑승항구']\n", "먼저 쓸 열 일곱 개를 features 리스트에 적어요. 앞 미션에서 남긴 그 일곱 열이죠."),
        ("code", "X=titanic[features].copy()\ny=titanic['생존'].astype(int)\n", "X는 titanic에서 features 열만 골라 copy한 거예요. copy를 붙여야 뒤에서 X를 고쳐도 원본이 안 바뀌거든요. y는 생존 열을 astype(int)로 정수로 만든 거예요."),
        ("code", "print(X.shape,y.shape)\nX.head()\n", "모양을 출력하고 X의 앞 다섯 줄을 봐요."),
        ("output", "X는 (1309, 7), y는 (1309,)이에요. 행 수가 같죠? 표를 보면 성별과 탑승항구는 글자고, 나이에는 빈칸이 있을 거예요. 그게 다음 단원 재료예요."),
        ("submit", "제출하면 X의 열 일곱 개와 y의 합 500, 생존자 수를 확인해요."),
    ],
    "column-types": [
        ("problem", "자, 다음 단원에서 숫자 열과 글자 열을 다르게 손질할 거라 미리 갈라 둬요. X에서 숫자 열 이름을 numeric_columns, 글자 열 이름을 category_columns에 담고 출력하면 돼요."),
        ("starter", "준비 코드가 titanic을 읽고 features, X, y까지 만들어 뒀어요. 그대로 둘게요."),
        ("code", "numeric_columns = list(X.select_dtypes('number').columns)\n", "select_dtypes('number')는 숫자 열만 남긴 표예요. 그 columns를 list로 감싸서 numeric_columns에 담아요."),
        ("code", "category_columns = list(X.select_dtypes(exclude='number').columns)\n", "exclude='number'를 주면 반대로 숫자가 아닌 열만 남아요. 그게 글자 열, 범주 열이죠."),
        ("code", "print(numeric_columns)\nprint(category_columns)\n", "두 리스트를 출력해요."),
        ("output", "숫자 열 다섯, 객실등급, 나이, 형제배우자, 부모자녀, 요금이에요. 글자 열은 성별, 탑승항구 둘이죠? 다섯과 둘이면 맞아요."),
        ("submit", "제출하면 두 리스트의 열 이름을 확인해요."),
    ],
    "get-dummies": [
        ("problem", "자, 모델은 여성, 남성 같은 글자를 못 먹어요. 값마다 열을 하나씩 만들어 해당하면 1, 아니면 0을 적는 게 One-hot이에요. pd.get_dummies로 성별 열을 바꿔 encoded에 담고 head를 보면 돼요."),
        ("hint", "만화를 보세요. 성별 하나가 성별_여성, 성별_남성 두 열로 갈라지죠? 각 행에서 둘 중 하나만 1이에요."),
        ("starter", "준비 코드는 titanic을 읽는 두 줄이에요. 그대로 둘게요."),
        ("code", "encoded = pd.get_dummies(titanic[['성별']])\n", "pd.get_dummies에 표를 넘겨요. 대괄호 두 겹으로 titanic[['성별']]을 써야 열 하나짜리 표가 되거든요. 값마다 새 열이 생겨요."),
        ("code", "print(encoded.shape)\nencoded.head()\n", "모양을 출력하고 앞 다섯 줄을 봐요."),
        ("output", "(1309, 2)가 나왔죠? 열이 성별_남성, 성별_여성 둘이에요. 표에는 True, False로 보이는데 True가 1이에요. 행마다 둘 중 하나만 True죠?"),
        ("submit", "제출하면 열 두 개와 행마다 합이 1인지 확인해요. 다음 단원의 OneHotEncoder가 같은 일을 모델 흐름 안에서 해요."),
    ],

    # ---- 분리와 전처리 Pipeline ----
    "fit-train": [
        ("title", "자, 이 단원에서 가장 중요한 한 문장이에요. 기준은 훈련 자료에서만 정한다."),
        ("앞 단원에서 입력 X와 정답 y를 만들었습니다", "앞 단원에 만든 X와 y를 훈련 자료와 테스트 자료로 나눠요. train_test_split에 맡기는데 인자 셋만 알면 돼요. test_size=0.2는 20%를 테스트로, stratify=y는 양쪽 생존 비율을 비슷하게, random_state=42는 누가 돌려도 똑같이 나뉘게 하는 고정 번호예요."),
        ("위젯: stratify", "위젯을 보세요. stratify를 끄면 우연히 한쪽에 생존자가 몰릴 수 있어요. 켜면 양쪽 비율이 같아지죠?"),
        ("제목: 기준은 훈련 자료에서만", "만화 그림을 보세요. 훈련 자료에는 fit_transform, 중앙값을 정하고 채워요. 테스트 자료에는 transform, 같은 중앙값으로 채우기만 해요."),
        ("나눈 다음에 손질을 시작합니다", "나눈 다음에 손질을 시작해요. 중앙값이 얼마인가, 어떤 값들이 있는가, 이렇게 기준을 정하는 일 자체가 자료를 들여다보는 학습이거든요. 테스트 나이까지 넣어 중앙값을 구하면 모의고사를 미리 본 셈, 작은 누수예요."),
        ("제목: 중앙값은 어디서 구하나", "민지 말처럼 1,309명 전체에서 구하면 더 정확할 것 같죠? 그 안에 테스트 262명이 들어 있어요. 기준은 훈련 1,047명에서만이에요."),
        ("scikit-learn의 손질 도구들은 이 구분을 메서드 이름으로 드러냅니다", "scikit-learn은 이 구분을 메서드 이름으로 드러내요. fit은 기준 정하기, transform은 적용하기, fit_transform은 둘을 한 번에. 그러니 훈련에는 fit_transform, 테스트에는 transform이에요."),
        ("train_values = imputer.fit_transform(X_train[['나이', '요금']])", "코드를 보세요. imputer를 중앙값 전략으로 만들고, 훈련에는 fit_transform, 테스트에는 같은 imputer로 transform만. 이 모양이 빈칸 채우기, One-hot, 표준화 전부에 똑같아요."),
        ("check", "확인 문항이요. 중앙값이나 값 목록 같은 기준을 어느 쪽에서만 정하냐. 문제집 쪽이죠."),
    ],
    "stratified-split": [
        ("problem", "자, X와 y를 train_test_split으로 나눠서 X_train, X_test, y_train, y_test 네 개를 만들어요. test_size=0.2, stratify=y, random_state=42예요. 두 쪽 행 수와 생존 비율을 출력하면 돼요."),
        ("hint", "만화를 보세요. 무작위로 나누다 테스트에 생존자가 몰리면 채점이 치우쳐요. stratify=y가 그걸 막고, random_state=42가 누가 돌려도 같게 해 주거든요."),
        ("starter", "준비 코드가 X, y까지 만들고 train_test_split도 불러왔어요. 그대로 둘게요."),
        ("code", "X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,stratify=y,random_state=42)\n", "train_test_split이 네 개를 순서대로 돌려줘요. 훈련 입력, 테스트 입력, 훈련 정답, 테스트 정답. 이 순서를 바꾸면 조용히 틀려요."),
        ("code", "print(len(X_train),len(X_test))\nprint(y_train.mean(),y_test.mean())\n", "행 수는 len으로, 생존 비율은 y의 mean으로 봐요. 0과 1의 평균이 곧 생존 비율이거든요."),
        ("output", "훈련 1047명, 테스트 262명이에요. 생존 비율은 둘 다 0.382, 거의 같죠? stratify 덕이에요."),
        ("submit", "제출하면 행 수와 두 비율의 차이가 1% 안인지 확인해요."),
    ],
    "first-model": [
        ("problem", "자, 손질을 배우기 전에 모델을 한 번 돌려 봐요. 빈칸 없고 이미 숫자인 객실등급, 형제배우자, 부모자녀 세 열만 써요. LogisticRegression을 만들고 학습해서 테스트 정확도를 accuracy에 담으면 돼요."),
        ("starter", "준비 코드가 분리까지 끝내고 simple에 세 열 이름을 담아 뒀어요. 그대로 둘게요."),
        ("code", "model = LogisticRegression(max_iter=1000)\n", "모델은 늘 세 단계예요. 먼저 만들기. LogisticRegression에 max_iter=1000을 줘서 model에 담아요."),
        ("code", "model.fit(X_train[simple], y_train)\n", "둘째, 학습. fit에 훈련 입력과 훈련 정답을 넣어요. X_train에서 simple 세 열만 골라 넣는 거예요."),
        ("code", "pred = model.predict(X_test[simple])\n", "셋째, 예측. predict에 테스트 입력을 넣으면 262명의 예측이 나와요. 정답은 안 보여 주죠."),
        ("code", "accuracy = accuracy_score(y_test, pred)\nprint(accuracy)\n", "accuracy_score에 테스트 정답과 예측을 넣으면 일치한 비율이에요. 그게 정확도죠."),
        ("output", "0.672, 약 67%예요. 재료가 셋뿐이니 높지 않죠? 이 숫자를 기억해 두세요. 남은 미션은 이걸 올리는 일이에요."),
        ("submit", "제출하면 model이 열 셋으로 배웠는지, accuracy가 맞게 계산됐는지 확인해요."),
    ],
    "train-imputer": [
        ("problem", "자, 나이와 요금의 빈칸을 채워요. SimpleImputer를 중앙값 전략으로 imputer에 만들고, 훈련 표의 나이, 요금에 fit_transform, 테스트 표의 같은 열에 transform한 결과를 train_values, test_values에 담아 shape를 출력하면 돼요."),
        ("starter", "준비 코드가 분리까지 끝내고 SimpleImputer를 불러왔어요. 그대로 둘게요."),
        ("code", "imputer=SimpleImputer(strategy='median')\n", "SimpleImputer에 strategy='median'을 줘요. 빈칸을 중앙값으로 채우는 도구예요."),
        ("code", "train_values=imputer.fit_transform(X_train[['나이','요금']])\n", "훈련에는 fit_transform이에요. 훈련 자료에서 나이와 요금의 중앙값을 정하고, 바로 채워요."),
        ("code", "test_values=imputer.transform(X_test[['나이','요금']])\n", "테스트에는 같은 imputer로 transform만 해요. 훈련에서 정한 중앙값으로 채우기만 하는 거예요. 여기서 fit을 다시 하면 기준이 바뀌어서 누수거든요."),
        ("code", "print(train_values.shape,test_values.shape)\n", "두 결과의 모양을 출력해요."),
        ("output", "(1047, 2)와 (262, 2)예요. 열 둘씩, 빈 값은 하나도 없어요. 훈련에서 정하고 테스트에는 적용만, 됐죠?"),
        ("submit", "제출하면 모양과 빈칸 여부, imputer의 중앙값이 훈련 자료 것인지 확인해요."),
    ],
    "onehot-fit": [
        ("problem", "자, 앞 단원의 get_dummies를 모델 흐름에 맞는 도구로 바꿔요. OneHotEncoder를 encoder에 만들고, 훈련 성별에 fit_transform, 테스트 성별에 transform한 결과를 train_encoded, test_encoded에 담아 shape를 출력하면 돼요."),
        ("starter", "준비 코드가 분리까지 끝내고 OneHotEncoder를 불러왔어요. 그대로 둘게요."),
        ("code", "encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)\n", "OneHotEncoder에 인자 둘이에요. handle_unknown='ignore'는 테스트에 처음 보는 값이 나와도 오류 대신 0으로 두라는 뜻, sparse_output=False는 보통 배열로 달라는 뜻이에요."),
        ("code", "train_encoded = encoder.fit_transform(X_train[['성별']])\n", "훈련에는 fit_transform. 어떤 값들이 있나, 여성과 남성이구나, 이걸 훈련에서 정하고 바로 바꿔요."),
        ("code", "test_encoded = encoder.transform(X_test[['성별']])\n", "테스트에는 transform만. 빈칸 채우기와 똑같은 모양이죠?"),
        ("code", "print(train_encoded.shape, test_encoded.shape)\n", "두 결과의 모양을 출력해요."),
        ("output", "(1047, 2)와 (262, 2)예요. 여성, 남성이라 열이 둘이죠? 행마다 둘 중 하나만 1이에요."),
        ("submit", "제출하면 모양과 encoder가 익힌 값 목록, 행마다 합이 1인지 확인해요."),
    ],
    "why-pipeline": [
        ("title", "자, 손질이 늘어나면 순서가 꼬여요. 그래서 한 줄로 묶는 도구를 배워요."),
        ("지금까지 손질 도구를 둘 썼습니다", "손질 도구를 둘 썼죠? 빈칸 채우기, One-hot. 실제로는 하나 더 필요해요. 나이는 0에서 80, 요금은 0에서 500이라 어떤 모델은 큰 숫자 열에 끌려가거든요. 그래서 평균 0, 퍼짐 1로 맞추는 표준화를 해요. 이것도 훈련에서 정하고 테스트에 적용하는 도구예요."),
        ("제목: 손질을 한 줄로 묶기", "그림을 보세요. 채우기, 표준화, 모델이 한 줄로 이어져 있죠? fit 한 번에 세 단계가 다 돌아가요."),
        ("손질이 셋이 되면 코드가 길어지고", "손질이 셋이 되면 fit_transform과 transform 짝을 셋 다 맞춰야 하고, 모델에 넣기 전에 다시 합쳐야 해요. 한 군데라도 테스트에 fit을 하면 조용히 누수가 생기는데, 오류가 안 나서 알아차리기 어렵거든요."),
        ("제목: 세 번의 손질, 한 번의 fit", "만화의 준호가 그 실수를 했죠? 셋을 순서대로 Pipeline에 넣어 두면, fit 한 번에 안에서 차례로 기준을 정하고 테스트엔 적용만 해요. 짝을 틀릴 자리가 없어져요."),
        ("Pipeline은 이 단계들을 순서대로 한 줄에 묶어 주는 도구입니다", "Pipeline은 단계들을 순서대로 한 줄에 묶어 주는 도구예요. 묶고 나면 fit 한 번, transform이나 predict 한 번이면 돼요."),
        ("1단계: 빈칸 채우기", "코드를 보세요. 이름과 도구 쌍을 리스트에 순서대로 넣어요. fill이 빈칸 채우기, scale이 크기 맞추기. 그 다음은 도구 하나처럼 fit_transform, transform이에요."),
        ("(이름, 도구) 쌍을 리스트에 순서대로 넣는 것이 전부입니다", "이게 전부예요. 다음 단원에서는 숫자용 묶음과 글자용 묶음을 합치고 끝에 모델까지 붙여서, fit 한 번으로 손질과 학습이 끝나는 완성형을 써요."),
        ("check", "확인 문항이요. 손질 단계를 순서대로 묶어 fit 한 번에 처리하는 도구 이름, 만화 서버에 적혀 있었죠."),
    ],
    "pipeline-build": [
        ("problem", "자, 빈칸 채우기와 표준화를 Pipeline으로 묶어 numeric_pipeline에 만들어요. 숫자 열 numeric에 대해 훈련은 fit_transform, 테스트는 transform해서 train_values, test_values에 담고 shape를 출력하면 돼요."),
        ("starter", "준비 코드가 분리까지 끝내고 세 도구를 불러왔어요. numeric에 숫자 열 다섯 개도 담겨 있어요. 그대로 둘게요."),
        ("code", "numeric_pipeline = Pipeline([('fill', SimpleImputer(strategy='median')), ('scale', StandardScaler())])\n", "Pipeline 괄호 안에 리스트, 리스트 안에 이름과 도구 튜플 둘이에요. fill은 중앙값 채우기, scale은 표준화. 이 순서대로 돌아가요."),
        ("code", "train_values = numeric_pipeline.fit_transform(X_train[numeric])\n", "묶은 걸 도구 하나처럼 써요. 훈련에는 fit_transform. 안에서 중앙값도, 평균과 퍼짐도 훈련 자료에서 정해요."),
        ("code", "test_values = numeric_pipeline.transform(X_test[numeric])\n", "테스트에는 transform만. 두 단계 다 적용만 하는 거예요."),
        ("code", "print(train_values.shape, test_values.shape)\n", "모양을 출력해요."),
        ("output", "(1047, 5)와 (262, 5)예요. 숫자 열 다섯 개죠? 표준화를 거쳤으니 훈련 자료는 열마다 평균이 0에 가까워요."),
        ("submit", "제출하면 모양과 빈칸 여부, 훈련 평균이 0인지, 단계 이름이 fill, scale인지 확인해요."),
    ],

    # ---- 세 분류 모델과 기준 비교 ----
    "baselines": [
        ("title", "자, 모델 세 개를 소개하고, 그 전에 꼭 재야 하는 기준 모델 이야기예요."),
        ("손질이 끝났으니 모델을 고를 차례입니다", "손질이 끝났으니 모델을 골라요. 세 가지를 쓸 건데, 수식 없이 각각 뭘 하는지만 잡으면 돼요."),
        ("로지스틱 회귀(LogisticRegression)는 입력마다 점수를 매겨", "로지스틱 회귀는 입력마다 점수를 매겨 더하고, 선을 넘으면 생존이에요. 설명이 쉽죠. 결정 트리는 스무고개예요. 질문을 끝없이 늘리면 훈련 자료를 통째로 외우니까 max_depth로 깊이를 제한해요. 랜덤 포레스트는 조금씩 다른 트리 수십 개의 다수결이라 보통 더 안정적이에요."),
        ("위젯: overfit", "위젯에서 깊이를 올려 보세요. 훈련 점수는 계속 오르는데 테스트 점수는 어느 지점부터 떨어지죠? 그게 외우기 시작하는 지점이에요."),
        ("모델이 몇 개든 비교 방식은 하나입니다", "비교 방식은 하나예요. 같은 훈련 자료로 배우고 같은 테스트 자료로 채점한다. 그런데 정확도 78%가 좋은 걸까요? 테스트 262명 중 사망이 162명이라 전원 사망으로 찍어도 62%거든요. 그래서 가장 많은 답만 찍는 DummyClassifier를 기준 모델로 먼저 돌려요."),
        ("제목: 팀장의 감과 모델", "만화를 보세요. 콜센터 팀장은 월요일 인력을 지난주 월요일과 같게 짜요. 그게 기준 모델이에요. 민지의 예측 모델이 이것보다 더 빗나가면 팀장의 감보다 못한 거죠."),
        ("model = Pipeline([('prepare', make_preprocessor()), ('model', LogisticRegression(max_iter=2000))])", "코드를 보세요. 손질기 뒤에 모델을 붙인 Pipeline이에요. fit 한 번에 손질과 학습, predict 한 번에 손질과 예측이 끝나요."),
        ("준비 코드의 make_preprocessor()는 앞 단원에서", "준비 코드의 make_preprocessor()가 앞 단원의 숫자용 묶음과 글자용 묶음을 합친 손질기예요. 모델을 바꿀 때는 model 자리만 바꾸면 돼요."),
        ("점수는 정확도(accuracy, 전체 중 맞힌 비율) 하나만 보지 않습니다", "점수는 정확도 하나만 보지 않아요. 생존자가 적은 자료라 생존자를 얼마나 잘 찾았는지 보는 F1도 같이 적어요. 뜻은 앞 단원에서 하고, 지금은 두 점수를 표에 나란히 적는다까지만이에요."),
        ("check", "확인 문항이요. 입력을 보지 않고 가장 많은 답만 찍는 기준 모델의 scikit-learn 이름이에요."),
    ],
    "dummy-only": [
        ("problem", "자, 기준 모델만 먼저 돌려요. DummyClassifier를 most_frequent 전략으로 dummy에 만들고, 훈련 자료로 학습해서 테스트 정확도를 dummy_accuracy에 담아 출력하면 돼요. 입력을 안 보니까 손질도 필요 없어요."),
        ("starter", "준비 코드가 분리까지 끝내고 DummyClassifier와 accuracy_score를 불러왔어요. 그대로 둘게요."),
        ("code", "dummy = DummyClassifier(strategy='most_frequent')\n", "DummyClassifier에 strategy='most_frequent'를 줘요. 가장 많은 답만 찍는 모델이에요."),
        ("code", "dummy.fit(X_train, y_train)\n", "fit은 형식상 해요. 훈련 정답에서 뭐가 가장 많은지만 세는 거예요. 사망이죠."),
        ("code", "dummy_accuracy = accuracy_score(y_test, dummy.predict(X_test))\nprint(dummy_accuracy)\n", "테스트를 예측하면 전부 0이 나와요. 그걸 테스트 정답과 비교한 비율이 dummy_accuracy예요."),
        ("output", "0.618, 약 62%예요. 테스트 262명 중 사망 162명이라 162 나누기 262죠. 이 숫자가 이 단원의 기준선이에요. 이걸 못 넘는 모델은 아무것도 못 배운 거예요."),
        ("submit", "제출하면 162 나누기 262와 같은지, 예측이 전부 0인지 확인해요."),
    ],
    "model-comparison": [
        ("problem", "자, 기준 모델과 세 모델을 같은 조건에서 비교해요. models 딕셔너리에 Dummy, Logistic, Tree, Forest를 넣고, 각각 손질기와 Pipeline으로 묶어 학습하고 예측해서 accuracy와 f1을 results 표에 모으면 돼요."),
        ("hint", "표 만들기 패턴이에요. 빈 리스트를 두고 반복문 안에서 Pipeline을 새로 만들고 fit, predict, 그리고 딕셔너리 한 줄을 append. 끝나면 DataFrame으로 바꿔요."),
        ("starter", "준비 코드가 분리와 make_preprocessor까지 다 해 놓고 모델 네 개와 점수 함수를 불러왔어요. 그대로 둘게요."),
        ("code", "models={'Dummy':DummyClassifier(strategy='most_frequent'),'Logistic':LogisticRegression(max_iter=2000),'Tree':DecisionTreeClassifier(max_depth=4,random_state=42),'Forest':RandomForestClassifier(n_estimators=50,max_depth=5,random_state=42)}\n", "models에 이름과 모델을 짝지어 넣어요. Dummy는 기준, Logistic은 반복 2000회, Tree는 깊이 4, Forest는 트리 50개에 깊이 5예요. random_state=42로 누가 돌려도 같게 해요."),
        ("code", "rows=[]\nfitted={}\n", "결과 줄을 모을 rows와 학습된 모델을 보관할 fitted를 비워 둬요."),
        ("code", "for name,estimator in models.items():\n    model=Pipeline([('prepare',make_preprocessor()),('model',estimator)])\n    model.fit(X_train,y_train)\n    pred=model.predict(X_test)\n    fitted[name]=model\n    rows.append({'model':name,'accuracy':accuracy_score(y_test,pred),'f1':f1_score(y_test,pred,zero_division=0)})\n", "반복문이에요. 모델마다 손질기와 묶은 Pipeline을 새로 만들고, 같은 훈련 자료로 fit, 같은 테스트 자료로 predict해요. 모델은 fitted에 보관하고, 이름과 두 점수를 딕셔너리로 rows에 붙여요. zero_division=0은 Dummy처럼 생존을 하나도 안 맞혀도 오류 대신 0을 주라는 거예요."),
        ("code", "results=pd.DataFrame(rows).set_index('model')\nresults\n", "rows를 DataFrame으로 바꾸고 model 열을 인덱스로 세워요. 마지막 줄에 results를 적으면 표로 보여요."),
        ("output", "표를 보세요. Dummy는 정확도 0.618에 F1이 0이에요. 앞 미션 기준선 그대로죠? Logistic은 0.809, Tree는 0.836, Forest는 0.844예요. 셋 다 기준을 넘었고, F1도 0.74에서 0.78 사이예요."),
        ("submit", "제출하면 네 모델 이름과 두 열, Dummy의 점수가 기준선과 같은지 확인해요."),
    ],
    "train-vs-test": [
        ("problem", "자, 외운 모델을 잡아내요. 깊이 제한 없는 DecisionTreeClassifier를 손질기와 묶어 학습하고, 정확도를 두 번 재요. 훈련 자료로 잰 train_accuracy, 테스트 자료로 잰 test_accuracy. 둘을 출력하면 돼요."),
        ("hint", "만화를 보세요. 문제집 1,047문제를 전부 외운 모델이 처음 보는 262문제에서 점수가 뚝 떨어지죠? 답을 외운 거지 규칙을 배운 게 아니에요. 그게 과적합이에요."),
        ("starter", "준비 코드가 분리와 손질기까지 해 놓고 DecisionTreeClassifier와 accuracy_score를 불러왔어요. 그대로 둘게요."),
        ("code", "model = Pipeline([('prepare', make_preprocessor()), ('model', DecisionTreeClassifier(random_state=42))])\n", "손질기 뒤에 결정 트리를 붙여요. max_depth를 안 주니까 질문을 끝없이 늘릴 수 있어요. 외우기 딱 좋은 조건이죠."),
        ("code", "model.fit(X_train, y_train)\n", "훈련 자료로 학습해요."),
        ("code", "train_accuracy = accuracy_score(y_train, model.predict(X_train))\n", "첫 번째 점수는 훈련 자료로 재요. 배운 자료를 그대로 다시 채점하는 거예요. 문제집 점수죠."),
        ("code", "test_accuracy = accuracy_score(y_test, model.predict(X_test))\nprint(train_accuracy, test_accuracy)\n", "두 번째 점수는 테스트 자료로 재요. 모의고사 점수예요. 둘을 나란히 출력해요."),
        ("output", "훈련 0.967, 테스트 0.798이에요. 문제집은 97%를 맞히는데 모의고사는 80%죠? 이 차이가 과적합이에요. 실력은 테스트 쪽이 더 가까워요."),
        ("submit", "제출하면 훈련 점수가 90%를 넘고 테스트 점수보다 높은지 확인해요."),
    ],
    "hyperparameters": [
        ("title", "자, max_depth 같은 숫자는 누가 정하냐. 공부 내용과 공부법 이야기예요."),
        ("앞 미션에서 질문 횟수를 max_depth로 제한하면", "앞 미션에서 max_depth로 질문을 제한하면 덜 외운다고 했죠? 모델 안에는 값이 두 종류예요. 학습하면서 기계가 스스로 찾는 값이 파라미터, 학습 전에 사람이 정해 주는 값이 하이퍼파라미터예요."),
        ("제목: 파라미터와 하이퍼파라미터", "그림을 보세요. 왼쪽 파라미터는 공부 내용, fit이 채워요. 오른쪽 하이퍼파라미터는 공부법, 괄호 안에 적어요. max_depth, n_estimators가 그쪽이죠."),
        ("제목: 공부 내용과 공부법", "민지 질문처럼 max_depth도 모델이 알아서 정하면 안 되냐. 공부 내용은 학생이 익히지만 하루 몇 시간, 어떤 방법으로 할지는 공부 전에 정하잖아요. 후보를 몇 개 시켜 보고 점수 좋은 쪽을 고르는 거예요."),
        ("for depth in [2, 3, 5, 8, 12]:", "코드를 보세요. 깊이 후보 다섯 개를 돌면서 cross_val_score로 채점해요. 훈련 자료 안에서 5번 나눠 채점한 평균이에요. 테스트는 안 건드려요."),
        ("고르는 방법이 튜닝입니다", "이게 튜닝이에요. 후보를 두고 훈련 자료 안에서 다시 나눠 채점한 교차 검증 점수로 비교해요. 테스트로 고르면 시험지를 보고 공부법을 고른 셈이라 안 돼요. GridSearchCV가 이 반복문을 대신 돌려 줘요."),
        ("한 가지 더. 파라미터는 처음부터 기계가 학습으로 찾는 값이었습니다", "요즘은 하이퍼파라미터와 모델 고르기까지 기계가 해요. 그게 AutoML이에요. 그래도 어떤 점수로 비교할지, 결과를 믿을지는 사람이 정해요. AI한테 max_depth 후보를 교차 검증으로 골라 줘, 이 한 줄을 보탤 수 있으면 돼요."),
        ("check", "확인 문항이요. 학습 전에 사람이 정해 주는 값, 공부법 쪽 이름이에요."),
    ],
    "tune-depth": [
        ("problem", "자, 공부법을 골라요. 깊이 후보 depths마다 손질기와 묶은 결정 트리를 cross_val_score 평균으로 채점해 cv_scores에 담고, 가장 높은 깊이를 best_depth로 골라요. 그 깊이로 다시 학습해 테스트 정확도를 test_accuracy에 담으면 돼요. 테스트는 고른 뒤 한 번만이에요."),
        ("starter", "준비 코드가 분리와 손질기까지 해 놓고 depths에 2, 3, 5, 8, 12를, cv_scores에 빈 딕셔너리를 둬 뒀어요. 그대로 둘게요."),
        ("code", "for depth in depths:\n    model = Pipeline([('prepare', make_preprocessor()), ('model', DecisionTreeClassifier(max_depth=depth, random_state=42))])\n    cv_scores[depth] = cross_val_score(model, X_train, y_train, cv=5).mean()\n", "후보마다 그 깊이의 트리를 손질기와 묶어 만들고, cross_val_score에 훈련 자료만 넣어요. cv=5니까 훈련 안에서 5번 나눠 채점한 평균이 cv_scores에 깊이별로 들어가요."),
        ("code", "best_depth = max(cv_scores, key=cv_scores.get)\n", "max에 key=cv_scores.get을 주면 값이 가장 큰 키, 곧 점수가 가장 높은 깊이가 나와요."),
        ("code", "model = Pipeline([('prepare', make_preprocessor()), ('model', DecisionTreeClassifier(max_depth=best_depth, random_state=42))])\nmodel.fit(X_train, y_train)\n", "고른 깊이로 모델을 새로 만들어 훈련 자료 전체로 다시 학습해요."),
        ("code", "test_accuracy = accuracy_score(y_test, model.predict(X_test))\n", "이제야 테스트 자료를 써요. 고르는 데는 안 썼으니 처음 보는 자료 그대로죠."),
        ("code", "print({depth: round(float(score), 3) for depth, score in cv_scores.items()})\nprint(f'고른 깊이 {best_depth}, 테스트 정확도 {test_accuracy:.3f}')\n", "깊이별 점수를 float로 바꿔 소수 셋째 자리로 출력하고, 고른 깊이와 테스트 정확도를 문장으로 출력해요."),
        ("output", "깊이 2는 0.768, 3은 0.806, 5는 0.793, 8은 0.772, 12는 0.726이에요. 깊을수록 좋은 게 아니죠? 고른 깊이는 3, 테스트 정확도는 0.836이에요. 앞 미션의 외운 트리 0.798보다 높아요."),
        ("submit", "제출하면 다섯 후보의 점수, best_depth가 최댓값의 키인지, model의 깊이가 그 값인지 확인해요."),
    ],
    "save-model": [
        ("title", "자, 한 번 배운 모델은 저장해서 다시 쓴다. 현장에서 꼭 필요한 이야기예요."),
        ("지금까지 모든 미션은 실행할 때마다 fit부터 다시 했습니다", "지금까진 실행마다 fit부터 다시 했죠? 1,047명이면 1초라 괜찮은데, 회사 자료는 수백만 행이고 훈련에 몇 시간이 걸려요. 예측할 때마다 다시 배울 이유가 없어요. 파일로 저장하고, 쓸 때는 불러와서 predict만 해요."),
        ("제목: 어제 훈련한 모델은 어디 갔나", "만화를 보세요. 빵 공장장이 어제 세 시간 훈련했는데 오늘 또 처음부터냐고 하죠? 프로그램이 끝나면 모델은 사라져요. joblib.dump로 파일에 넣어 두면 내일 새벽엔 불러와서 예측만 하면 돼요."),
        ("joblib.dump(model, 'titanic_model.joblib')", "코드를 보세요. dump가 저장, load가 불러오기예요. 불러온 모델은 훈련 없이 바로 predict해요."),
        ("joblib은 scikit-learn과 함께 설치되는 저장 도구입니다", "저장하는 건 모델 하나가 아니라 파이프라인 전체예요. 그래서 나이 중앙값, One-hot 열 목록, 표준화 기준도 파일 안에 같이 들어가요. 새 자료에도 같은 손질이 그대로 적용되죠. 한 줄로 묶어 둔 또 하나의 이유예요."),
        ("현장에서는 이렇게 돌아갑니다", "현장은 이래요. 빵 공장은 매주 월요일 한 번 다시 훈련해 파일을 갈아 끼우고, 매일 새벽엔 불러와서 오늘 생산량만 예측해요. AI한테 시킬 때도 모델은 파일로 저장하고 예측 스크립트는 불러오기만 하게, 이 한 줄을 보태면 돼요."),
        ("주의할 점 두 가지", "주의할 점 둘이에요. 같은 버전의 scikit-learn에서 열어야 안전하고, 자료가 많이 바뀌면 다시 훈련해야 해요. 파일은 그때 배운 규칙일 뿐이거든요."),
        ("check", "확인 문항이요. 훈련 끝난 파이프라인을 파일로 저장하는 joblib 함수, 공장장이 말했죠."),
    ],
    "save-and-load": [
        ("problem", "자, 로지스틱 회귀를 손질기와 묶어 model에 학습하고 joblib.dump로 titanic_model.joblib에 저장해요. 그다음 joblib.load로 loaded에 다시 불러와서 테스트 정확도를 test_accuracy에 담아 출력하면 돼요. 저장과 불러오기 사이에 훈련은 없어요."),
        ("starter", "준비 코드가 분리와 손질기까지 해 놓고 joblib, LogisticRegression, accuracy_score를 불러왔어요. 그대로 둘게요."),
        ("code", "model = Pipeline([('prepare', make_preprocessor()), ('model', LogisticRegression(max_iter=1000))])\nmodel.fit(X_train, y_train)\n", "손질기 뒤에 로지스틱 회귀를 붙인 Pipeline을 만들고 훈련 자료로 학습해요. 여기까지는 늘 하던 거죠."),
        ("code", "joblib.dump(model, 'titanic_model.joblib')\n", "joblib.dump에 모델과 파일 이름을 넣어요. 파이프라인 전체가 파일로 들어가요. 손질 기준까지요."),
        ("code", "loaded = joblib.load('titanic_model.joblib')\n", "joblib.load로 그 파일을 다시 읽어 loaded에 담아요. 다른 날, 다른 프로그램에서 하는 일을 지금 흉내 내는 거예요."),
        ("code", "test_accuracy = accuracy_score(y_test, loaded.predict(X_test))\nprint(f'불러온 모델의 테스트 정확도: {test_accuracy:.3f}')\n", "불러온 loaded로 테스트를 예측해 정확도를 재요. fit은 다시 안 해요. 그걸 문장으로 출력해요."),
        ("output", "불러온 모델의 테스트 정확도 0.809예요. 앞 비교표의 Logistic과 같은 숫자죠? 저장하고 불러와도 예측이 그대로예요."),
        ("submit", "제출하면 파일이 생겼는지, loaded와 model의 예측이 완전히 같은지 확인해요."),
    ],

    # ---- 5장 도전 과제 ----
    "full-comparison": [
        ("problem", "자, 5장을 한 번에 복습해요. 이번엔 준비 코드가 거의 없어요. 자료 읽기부터 X와 y, 층화 분할, 손질기, 네 모델 비교표까지 직접 써요. 순서를 틀리면 조용한 누수가 생기니까 하나씩 가요."),
        ("hint", "앞 단원의 make_preprocessor를 떠올리세요. 숫자 열 다섯은 중앙값 채우기와 표준화, 글자 열 둘은 최빈값 채우기와 One-hot이에요. Pipeline은 모델마다 새로 만들고, best_model은 results의 f1에서 idxmax예요."),
        ("starter", "준비 코드는 import 열한 줄뿐이에요. 그대로 둘게요."),
        ("code", "titanic = pd.read_csv('data/titanic.csv')\nfeatures = ['객실등급','성별','나이','형제배우자','부모자녀','요금','탑승항구']\nX = titanic[features].copy()\ny = titanic['생존'].astype(int)\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)\n", "앞 두 단원 그대로예요. 자료를 읽고, 사고 전에 알 수 있는 일곱 열로 X, 생존을 정수로 y. 그리고 test_size=0.2, stratify=y, random_state=42로 나눠요. 손질보다 분할이 먼저죠."),
        ("code", "preprocessor = ColumnTransformer([\n    ('numeric', Pipeline([('fill', SimpleImputer(strategy='median')), ('scale', StandardScaler())]), ['객실등급','나이','형제배우자','부모자녀','요금']),\n    ('category', Pipeline([('fill', SimpleImputer(strategy='most_frequent')), ('encode', OneHotEncoder(handle_unknown='ignore'))]), ['성별','탑승항구']),\n])\n", "손질기예요. ColumnTransformer에 묶음 둘을 넣어요. numeric은 숫자 열 다섯에 중앙값 채우기와 표준화, category는 성별과 탑승항구에 최빈값 채우기와 One-hot이에요. 이름, 묶음, 열 목록, 이 셋이 한 쌍이에요."),
        ("code", "models = {\n    'Dummy': DummyClassifier(strategy='most_frequent'),\n    'Logistic': LogisticRegression(max_iter=2000),\n    'Tree': DecisionTreeClassifier(max_depth=5, random_state=42),\n    'Forest': RandomForestClassifier(n_estimators=50, max_depth=5, random_state=42),\n}\n", "모델 넷이에요. Dummy는 가장 많은 답 찍기, 기준 모델이죠. Logistic은 반복 2000회, Tree는 깊이 5, Forest는 트리 50개에 깊이 5, 난수 42예요."),
        ("code", "rows = {}\nfor name, model in models.items():\n    pipeline = Pipeline([('prepare', preprocessor), ('model', model)])\n    pipeline.fit(X_train, y_train)\n    pred = pipeline.predict(X_test)\n    rows[name] = {'accuracy': accuracy_score(y_test, pred), 'f1': f1_score(y_test, pred)}\n", "반복문이에요. 모델마다 손질기와 묶은 Pipeline을 새로 만들어 같은 훈련 자료로 fit, 같은 테스트 자료로 predict해요. preprocessor는 같은 걸 다시 써도 돼요. 매번 훈련 자료로 다시 fit되거든요. 이름마다 accuracy와 f1을 rows에 담아요."),
        ("code", "results = pd.DataFrame(rows).T\nbest_model = results['f1'].idxmax()\nprint(best_model)\nresults\n", "rows를 DataFrame으로 바꾸면 모델이 열로 서니까 T로 뒤집어 행으로 세워요. f1이 가장 높은 행 이름이 best_model이에요. 그걸 출력하고 마지막 줄에 results를 적어요."),
        ("output", "best_model은 Forest예요. 표를 보세요. Dummy는 정확도 0.618에 F1 0, 162 나누기 262 그대로죠? Logistic 0.809, Tree 0.832, Forest 0.844예요. F1은 Forest가 0.781로 가장 높아요."),
        ("submit", "제출하면 X와 y, 분할 행 수, 표의 네 행 두 열, Dummy가 기준선과 같은지, best_model이 Dummy가 아닌지 확인해요."),
    ],
}
