"""해설 모드 scripts for chapter 2 (pandas): what the tutor says and types for each concept and
coding problem of the three units (files, missing, html) and the chapter's challenge, keyed by
activity id. Format and rules: narration.py.

Voice: the instructor's (see .scratch/presenter-decks/spec.md): 해요체 구어, "자," opens a scene,
one or two short sentences per line, says what the student should look at right now.
"""

NARRATION = {
    # ---- CSV·Excel과 행·열 선택 ----
    "file-table": [
        ("title", "자, 이 단원은 파일이에요. 표를 파일로 저장하고, 파일을 표로 다시 여는 법이요."),
        ("앞 단원의 표는 코드 안에 직접 적은 종목 세 개였습니다", "지금까지 표는 코드 안에 직접 적었죠? 진짜 분석은 남이 만든 파일에서 시작해요. 거래 내역은 Excel, 주가는 CSV로 오거든요."),
        ("제목: 어디서 왔든 읽고 나면 같은 표", "만화를 보세요. CSV는 read_csv, Excel은 read_excel. 들어오는 길은 달라도 DataFrame이 된 뒤에는 똑같이 다뤄요."),
        ("CSV는 값을 쉼표로 구분해 한 줄에 한 행씩 적은", "CSV는 쉼표로 값을 나눈 글자 파일이에요. 메모장으로 열어도 읽혀요. Excel은 시트와 서식이 있어 복잡하지만, pandas로 읽으면 둘 다 같은 표가 돼요."),
        ("orders.to_csv('orders.csv', index=False)", "코드를 보세요. to_csv로 저장하고 read_csv로 다시 읽어요. 남이 만든 파일도 경로만 넘기면 똑같이 읽히죠."),
        ("저장할 때 index=False를 붙이는 이유가 있습니다", "index=False가 중요해요. 표에는 0, 1, 2 행 번호가 붙어 있는데, 이걸 같이 저장하면 다시 읽을 때 이름 없는 열이 하나 더 생겨요. 번호는 데이터가 아니니 빼고 저장해요."),
        ("읽어 온 표가 어떻게 생겼는지 확인하는 세 가지는 늘 같습니다", "읽어 오면 세 가지를 확인해요. head()로 앞 5행, shape로 몇 행 몇 열, columns로 열 이름. 그다음 열은 이름으로, 행은 iloc 자리 번호나 loc 조건으로 골라요."),
        ("check", "확인 문항이요. 저장할 때 행 번호를 빼는 옵션, 방금 코드에 있었죠?"),
    ],
    "inspect-frame": [
        ("problem", "자, 첫 미션은 표의 크기와 열 이름 확인이에요. 준비된 orders 표의 행 수, 열 수, 열 이름 리스트를 세 변수에 담아 출력하면 돼요."),
        ("starter", "준비 코드가 orders 표를 만들어 뒀어요. 거래 네 건이고, C의 가격이 비어 있다는 점 눈여겨보세요."),
        ("code", "n_rows, n_columns = orders.shape\ncolumn_names = list(orders.columns)\n", "orders.shape는 (4, 3) 같은 쌍이라 두 변수에 한 번에 나눠 담아요. 열 이름은 orders.columns를 list로 감싸 리스트로 만들어요."),
        ("code", "print(n_rows, n_columns, column_names)\n", "세 값을 쉼표로 이어 한 줄에 출력해요."),
        ("output", "4 3 그리고 product, price, quantity가 나왔죠? 4행 3열이에요."),
        ("submit", "제출할게요. 검사는 세 변수의 값을 봐요."),
    ],
    "to-csv": [
        ("problem", "자, 이번엔 저장이에요. orders를 orders.csv로 저장하고, 그 파일을 다시 읽어 saved에 담아요. 저장할 때 index=False를 꼭 붙여요."),
        ("starter", "준비 코드의 orders 표는 그대로 둘게요."),
        ("code", "orders.to_csv('orders.csv', index=False)\n", "to_csv에 파일 이름을 넘기고 index=False를 붙여요. 이걸 빼면 행 번호가 데이터처럼 저장돼서 다시 읽을 때 열이 하나 늘거든요."),
        ("code", "saved = pd.read_csv('orders.csv')\nsaved\n", "read_csv로 같은 파일을 다시 읽어 saved에 담아요. 마지막 줄에 saved만 적으면 앱이 표로 보여 줘요."),
        ("output", "4행 3열 표가 그대로 나왔죠? price가 10000.0처럼 소수로 보이는 건 빈 칸이 하나 있어서 그래요. 열 수가 4면 index=False를 빠뜨린 거예요."),
        ("submit", "제출할게요. 파일이 실제로 생겼는지, saved가 4행 3열인지 봐요."),
    ],
    "csv-excel": [
        ("problem", "자, 같은 표를 CSV와 Excel 두 형식으로 저장하고 각각 다시 읽어요. 형식이 달라도 읽고 나면 같은 DataFrame이라는 걸 눈으로 확인하는 거예요."),
        ("starter", "준비 코드의 orders 표는 그대로 둘게요."),
        ("code", "orders.to_csv('orders.csv',index=False)\norders.to_excel('orders.xlsx',index=False)\n", "저장 두 줄이요. to_csv와 to_excel, 확장자만 다르고 쓰는 법은 같아요. 둘 다 index=False예요."),
        ("code", "csv_df=pd.read_csv('orders.csv')\nexcel_df=pd.read_excel('orders.xlsx')\n", "읽기도 두 줄이요. read_csv와 read_excel로 각각 읽어 csv_df, excel_df에 담아요."),
        ("code", "print(csv_df.shape, excel_df.shape)\ncsv_df\n", "두 표의 크기를 나란히 출력하고, 마지막 줄에 csv_df를 적어 표를 봐요."),
        ("output", "(4, 3) (4, 3), 크기가 똑같죠? 아래 표도 원래 orders와 같아요. 어디서 왔든 표가 된 다음은 같다, 이거예요."),
        ("submit", "제출할게요. 두 표의 크기와 product 열이 같은지 봐요."),
    ],
    "series-vs-frame": [
        ("problem", "자, 대괄호 한 겹과 두 겹의 차이예요. orders['price']와 orders[['price']]를 각각 변수에 담고 type을 출력해 봐요."),
        ("starter", "준비 코드의 orders 표는 그대로 둘게요."),
        ("code", "price_series = orders['price']\nprice_frame = orders[['price']]\n", "한 겹은 열 하나를 세로줄로 꺼내는 거고, 두 겹은 이 이름들의 열로 된 표를 달라는 뜻이에요. 안쪽 대괄호가 열 이름 리스트거든요."),
        ("code", "print(type(price_series))\nprint(type(price_frame))\n", "type으로 자료구조 이름을 확인해요."),
        ("output", "pandas.Series와 pandas.DataFrame이 나왔죠? 열 하나에 sum이나 mean을 할 땐 한 겹, 열 여러 개를 표로 쓸 땐 두 겹이에요."),
        ("submit", "제출할게요. 하나는 Series, 하나는 DataFrame인지 봐요."),
    ],
    "selection": [
        ("problem", "자, 표에서 필요한 부분만 잘라 내요. product와 price 두 열만 고른 표를 selected에, 첫 두 행만 고른 표를 first_two에 담아요."),
        ("starter", "준비 코드의 orders 표는 그대로 둘게요."),
        ("code", "selected=orders[['product','price']]\n", "열 여러 개는 이름 리스트로 골라요. 그러니까 대괄호 두 겹이죠."),
        ("code", "first_two=orders.iloc[:2]\n", "행을 자리 번호로 고를 땐 iloc이에요. 리스트와 같은 규칙이라 끝 번호 2는 안 들어가고 0번, 1번만 남아요."),
        ("code", "print(selected.shape,first_two.shape)\nselected\n", "두 표의 크기를 출력하고 selected를 표로 봐요."),
        ("output", "(4, 2) (2, 3)이 나왔죠? selected는 4행 2열, first_two는 2행 3열이에요. 아래 표엔 product와 price만 남았어요."),
        ("submit", "제출할게요. selected의 열 이름과 first_two의 제품이 A, B인지 봐요."),
    ],
    "loc-condition": [
        ("problem", "자, 이번엔 자리 번호가 아니라 조건으로 행을 골라요. 수량이 3 이상인 거래만 many에 담고 표로 확인해요."),
        ("starter", "준비 코드의 orders 표는 그대로 둘게요."),
        ("code", "many = orders.loc[orders['quantity'] >= 3]\nmany\n", "orders['quantity'] >= 3은 행마다 참 거짓을 매긴 거예요. 그걸 loc 안에 넣으면 참인 행만 남아요. 앞 단원의 if가 표 전체에 한꺼번에 걸리는 셈이죠."),
        ("output", "제품 A 두 건, 수량 3과 4만 남았죠? 왼쪽 행 번호가 0과 2인 것도 보세요. 원래 자리 번호가 그대로 따라와요."),
        ("submit", "제출할게요."),
    ],
    "read-csv-titanic": [
        ("problem", "자, 이제 진짜 파일이에요. 앱이 준비한 data/titanic.csv를 읽어 titanic에 담고, shape를 출력한 뒤 head()로 앞 5행을 봐요."),
        ("starter", "준비 코드는 import 한 줄뿐이에요. 그대로 둘게요."),
        ("code", "titanic = pd.read_csv('data/titanic.csv')\n", "read_csv에 경로를 따옴표로 감싸 넘겨요. 자료가 data 폴더 안에 있어서 data/를 빼면 파일을 못 찾아요."),
        ("code", "print(titanic.shape)\ntitanic.head()\n", "shape를 출력하고 마지막 줄에 head()를 적어요. 앞 5행이 표로 떠요."),
        ("output", "(1309, 14), 1309명에 열이 14개예요. 열 이름을 훑어 보세요. 객실등급, 생존, 이름, 성별, 나이, 요금. 이 표가 분류 챕터까지 우리 주인공이에요."),
        ("submit", "제출할게요. titanic이 1309행 14열인지 봐요."),
    ],

    # ---- 조건 필터와 결측치 ----
    "missing-values": [
        ("title", "자, 이 단원 주제는 빈칸이에요. 빈칸은 0이 아니다, 이 한 문장이요."),
        ("앞 단원의 orders 표에는 가격이 비어 있는 거래가 한 건 있었습니다", "설문지에 나이 칸을 비워 둔 사람, 그 사람 나이가 0살일까요? 아니죠, 모른다예요. 이 빈 칸을 결측이라 부르고 pandas는 NaN으로 표시해요. 0과 섞으면 평균이 엉뚱하게 내려가요."),
        ("제목: 빈칸은 0이 아니다", "만화를 보세요. 나이 빈칸을 0으로 채우면 0살 고객이 생기고 평균 나이가 확 내려가요. 모른다로 두고 먼저 몇 개인지 세는 거예요."),
        ("그러니 분석을 시작하기 전에 어디가 얼마나 비어 있는지부터 셉니다", "그래서 분석 전에 어디가 얼마나 비었는지부터 세요. isna()가 빈 칸을 True로 표시하고, 거기에 sum을 붙이면 열마다 결측 개수가 나와요."),
        ("filled = orders['price'].fillna(12000)", "코드 세 줄이요. 첫 줄이 세기, 둘째 줄 fillna가 채우기, 셋째 줄 dropna가 그 행 빼기예요."),
        ("비어 있는 칸을 다루는 길은 두 가지뿐입니다", "빈 칸을 다루는 길은 채우거나 빼거나, 둘뿐이에요. 무엇으로 채울지는 사람이 정하는데 흔히 중앙값을 써요. 그리고 fillna와 dropna는 새 표를 돌려줄 뿐 원본은 그대로예요. 변수에 받아 둬야 해요."),
        ("제목: 빈칸을 0으로 넣으면", "빵 공장 만화요. 화요일 판매량을 안 적었는데 0으로 넣으면, 한 개도 못 판 날이 돼 버려요. 모르면 모른다로 두고 중앙값으로 채우거나 그 날을 빼는 거예요."),
        ("조건으로 행을 고르는 일도 한 단계 늘어납니다", "조건도 하나 늘어요. 두 조건을 합칠 땐 각각 괄호로 감싸고 그리고는 &, 또는은 |로 이어요. 괄호를 빼면 계산 순서가 달라져 오류가 나요."),
        ("both = orders.loc[(orders['price'] >= 12000) & (orders['quantity'] >= 2)]", "코드를 보세요. 괄호, &, 괄호. 아래 줄은 괄호, |, 괄호. 이 모양 그대로 외워 두면 돼요."),
        ("check", "확인 문항이요. 표에서 비어 있는 칸을 부르는 말, 이 단원 제목에 있었죠?"),
    ],
    "count-missing": [
        ("problem", "자, 빈 칸 세기부터요. orders에서 열마다 결측이 몇 개인지 missing_counts에 담고, 그중 price 열의 개수를 정수로 n_missing_price에 담아 출력해요."),
        ("starter", "준비 코드의 orders 표는 그대로 둘게요. C의 가격이 비어 있죠."),
        ("code", "missing_counts = orders.isna().sum()\n", "isna()가 빈 칸을 True로 표시하고 sum이 열마다 True를 세요. 결과는 열 이름으로 꺼내는 Series예요."),
        ("code", "n_missing_price = int(missing_counts['price'])\n", "missing_counts['price']로 가격 열 값을 꺼내고 int로 감싸 정수로 만들어요."),
        ("code", "print(missing_counts)\nprint(n_missing_price)\n", "둘 다 출력해요."),
        ("output", "product 0, price 1, quantity 0, 그리고 1이 나왔죠? 가격 열에만 하나 비어 있어요."),
        ("submit", "제출할게요."),
    ],
    "fill-median": [
        ("problem", "자, 첫 번째 길, 채우기예요. price의 중앙값을 median_price에 담고, 빈 칸을 그 값으로 채운 열을 filled_price에 담아 출력해요. 원본 orders는 건드리지 않아요."),
        ("starter", "준비 코드의 orders 표는 그대로 둘게요."),
        ("code", "median_price = orders['price'].median()\n", "median()은 빈 칸을 빼고 중앙값을 구해요. 10000, 12000, 20000 중 한가운데니까 12000이죠."),
        ("code", "filled_price = orders['price'].fillna(median_price)\n", "fillna는 빈 칸만 그 값으로 바꾼 새 열을 돌려줘요. 원본은 그대로라서 변수에 받아야 해요."),
        ("code", "print(median_price)\nprint(filled_price)\n", "중앙값과 채운 열을 출력해요."),
        ("output", "12000.0, 그리고 10000, 20000, 12000, 12000이 나왔죠? 마지막 칸이 중앙값으로 채워졌어요. orders의 빈 칸은 그대로예요."),
        ("submit", "제출할게요. 검사는 원본 orders에 빈 칸이 여전히 하나인지도 봐요."),
    ],
    "drop-missing": [
        ("problem", "자, 두 번째 길, 빼기예요. 가격이 비어 있는 행을 제외한 표를 dropped에, 남은 행 수를 n_left에 담아 출력하고 표도 봐요."),
        ("starter", "준비 코드의 orders 표는 그대로 둘게요."),
        ("code", "dropped = orders.dropna(subset=['price'])\n", "dropna에 subset으로 price를 주면 가격이 빈 행만 빼요. subset을 빼면 어느 열이든 빈 행을 다 빼는데, 열이 많은 표에선 크게 달라져요."),
        ("code", "n_left = len(dropped)\nprint(n_left)\ndropped\n", "len으로 남은 행 수를 세고, 출력한 뒤 마지막 줄에 dropped를 적어요."),
        ("output", "3이 나오고 아래 표엔 A, B, A 세 건만 남았죠? C가 빠졌어요."),
        ("submit", "제출할게요."),
    ],
    "filter-orders": [
        ("problem", "자, 조건 두 개를 모두 만족하는 거래요. 가격 12000 이상이고 수량 2 이상인 행을 selected에 담아요. 열 세 개는 유지하고 끝에 .copy()를 붙여요."),
        ("starter", "준비 코드의 orders 표는 그대로 둘게요."),
        ("code", "selected=orders.loc[(orders['price']>=12000)&(orders['quantity']>=2),['product','price','quantity']].copy()\nselected\n", "조건마다 괄호로 감싸고 &로 이어요. loc의 쉼표 뒤에 열 이름 리스트를 넣으면 행과 열을 한 번에 고르고, copy()는 뒤에서 고쳐도 원본이 안 바뀌게 해요."),
        ("output", "B와 A 두 건, 수량 2와 4가 남았죠? 가격이 빈 C는 비교 자체가 안 돼서 빠져요."),
        ("submit", "제출할게요."),
    ],
    "or-filter": [
        ("problem", "자, 이번엔 또는이에요. 제품이 A이거나 수량이 1인 거래를 either에 담고 표로 확인해요."),
        ("starter", "준비 코드의 orders 표는 그대로 둘게요."),
        ("code", "either = orders.loc[(orders['product'] == 'A') | (orders['quantity'] == 1)]\neither\n", "&가 그리고, |가 또는이에요. 괄호는 똑같이 조건마다 쳐요. 괄호가 없으면 'A' | orders['quantity']를 먼저 계산하려다 오류가 나거든요."),
        ("output", "A, A, C 세 건이 남았죠? 앞의 둘은 제품이 A라서, C는 수량이 1이라서 들어왔어요."),
        ("submit", "제출할게요."),
    ],
    "missing-totals": [
        ("problem", "자, 두 길을 나란히 비교해요. 중앙값으로 채운 filled와 빈 행을 뺀 dropped를 만들고, 각각 가격 곱하기 수량 열 amount를 만들어 합계를 비교해요."),
        ("starter", "준비 코드의 orders 표는 그대로 둘게요."),
        ("code", "filled=orders.copy()\nfilled['price']=filled['price'].fillna(filled['price'].median())\nfilled['amount']=filled['price']*filled['quantity']\n", "먼저 채우기 길이요. orders를 copy해서 filled를 만들고, price의 빈 칸을 중앙값으로 채운 뒤 amount 열을 만들어요. 열끼리 곱하면 행마다 계산돼요."),
        ("code", "dropped=orders.dropna(subset=['price']).copy()\ndropped['amount']=dropped['price']*dropped['quantity']\n", "다음은 빼기 길이요. dropna로 가격이 빈 행을 뺀 표에 copy()를 붙여 dropped를 만들고, 같은 amount 열을 만들어요."),
        ("code", "filled_total=filled['amount'].sum()\ndropped_total=dropped['amount'].sum()\n", "두 표의 amount를 각각 sum해서 합계 둘을 만들어요."),
        ("code", "print(filled_total,dropped_total)\nfilled\n", "두 합계를 나란히 출력하고 filled를 표로 봐요."),
        ("output", "130000과 118000, 12000 차이가 나죠? 어느 쪽도 진짜 전체 금액은 아니에요. 빈 칸 하나를 어떻게 다루기로 했는지에 따라 답이 달라지니까, 보고서에는 그 선택을 적어야 해요."),
        ("submit", "제출할게요. 두 합계와 두 표의 행 수를 봐요."),
    ],

    # ---- 저장 HTML에서 데이터 수집 ----
    "html-selectors": [
        ("title", "자, 이 단원은 웹 페이지예요. 글자 덩어리에서 우리가 원하는 칸 두 개만 집어내요."),
        ("지금까지의 표는 파일로 받았습니다", "어떤 숫자는 파일이 아니라 웹 페이지에만 있어요. 포털 시세 화면이 그렇죠. 화면의 정체는 HTML이라는 글자 파일인데, 광고, 메뉴, 제목이 수천 줄 섞여 있어요. 거기서 가격만 집어내는 게 이 단원 일이에요."),
        ("제목: 수집은 네 단계", "만화를 보세요. 수집은 네 단계예요. 선택자로 찾고, 글자를 꺼내고, 숫자로 바꾸고, 표에 모아요."),
        ("HTML은 <li>, <span>처럼 꺾쇠로 감싼", "HTML은 꺾쇠로 감싼 태그로 내용을 묶어요. 앱이 준비한 prices.html은 종목 하나가 li 하나고, 그 안에 이름 span과 가격 b가 있어요."),
        ('<li data-code="A"><span class="name">가상A</span><b>10,000</b></li>', "실제 파일이에요. ul의 id가 prices, li에 data-code 속성, span의 class가 name, b 안에 10,000. 이 구조를 눈에 담아 두세요."),
        ("원하는 태그를 집어내는 주소 표기법이 선택자(selector)입니다", "태그를 집어내는 주소가 선택자예요. 샵은 id, 점은 class, 공백은 그 안의. 그러니 #prices li는 prices 안의 모든 li죠. BeautifulSoup으로 읽어 두면 select로 전부, select_one으로 첫 하나를 꺼내요."),
        ("items = soup.select('#prices li')", "코드를 보세요. select로 li 두 개를 찾고, 첫 번째에서 select_one('.name')으로 이름, get_text(strip=True)로 글자만 뽑아요."),
        ("마지막 줄에 함정이 하나 있습니다", "마지막 줄이 함정이에요. 뽑은 가격은 '10,000'이라는 글자고 쉼표까지 있어서 int를 바로 하면 오류가 나요. replace로 쉼표를 지운 뒤 int를 거쳐야 숫자가 돼요."),
        ("실제 포털 사이트에 접속하는 대신 저장해 둔 문서로 연습하는 이유는 하나입니다", "실제 사이트 대신 저장한 문서로 연습하는 이유는 하나예요. 사이트는 구조가 자주 바뀌어서 어제 되던 선택자가 오늘 빈 결과를 내거든요. 원리는 같으니 네 단계를 먼저 몸에 익혀요."),
        ("check", "확인 문항이요. #prices li 같은 주소 표기법을 뭐라고 부르는지, 방금 봤죠?"),
    ],
    "string-to-int": [
        ("problem", "자, 네 단계 중 세 번째, 글자를 숫자로 고치는 단계만 따로 연습해요. price_text에 '10,000'이 들어 있어요. 쉼표를 지우고 int로 바꿔 price에 담고 price 곱하기 3을 출력해요."),
        ("starter", "준비 코드 한 줄, price_text = '10,000'은 그대로 둘게요."),
        ("code", "price = int(price_text.replace(',', ''))\n", "안쪽부터 읽어요. replace가 쉼표를 빈 글자로 바꿔 '10000'을 만들고, 그걸 int로 감싸요. 순서를 바꿔 int를 먼저 하면 ValueError가 나요."),
        ("code", "print(price * 3)\n", "숫자가 됐으니 곱셈이 돼요. 3을 곱해 출력해요."),
        ("output", "30000이 나왔죠? 글자였으면 '10,00010,00010,000'이 됐을 거예요."),
        ("submit", "제출할게요. price가 정수 10000인지 봐요."),
    ],
    "select-one": [
        ("problem", "자, 선택자로 요소를 찾아요. #prices li가 몇 개인지 n_items에, 첫 종목의 이름을 first_name에 담아 출력해요."),
        ("starter", "준비 코드가 prices.html을 읽어 soup까지 만들어 뒀어요. 그대로 둘게요."),
        ("code", "items = soup.select('#prices li')\nn_items = len(items)\n", "select는 맞는 요소를 리스트로 돌려줘요. 그러니 len으로 세면 되죠."),
        ("code", "first_name = items[0].select_one('.name').get_text(strip=True)\n", "첫 요소 [0]에서 select_one('.name')으로 이름 요소를 찾고, get_text(strip=True)로 글자만 꺼내요. strip은 앞뒤 공백을 지워요."),
        ("code", "print(n_items, first_name)\n", "둘을 한 줄에 출력해요."),
        ("output", "2 가상A가 나왔죠? li가 두 개고 첫 종목 이름이 가상A예요."),
        ("submit", "제출할게요."),
    ],
    "select-prices": [
        ("problem", "자, 두 종목의 가격을 전부 뽑아 숫자 리스트로 만들어요. #prices li b로 가격 요소를 모두 찾고, 하나씩 글자를 꺼내 쉼표를 지우고 int로 바꿔 prices에 모아요."),
        ("starter", "준비 코드가 soup까지 만들어 뒀어요. 그대로 둘게요."),
        ("code", "prices = []\nfor tag in soup.select('#prices li b'):\n    prices.append(int(tag.get_text(strip=True).replace(',', '')))\n", "빈 리스트를 만들고 for로 b 요소를 하나씩 돌아요. 안에서는 글자 꺼내기, 쉼표 지우기, int, append. 앞 단원의 for와 append가 그대로 쓰이죠."),
        ("code", "print(prices)\n", "리스트를 출력해요."),
        ("output", "[10000, 20000]이 나왔죠? 쉼표 없는 정수 둘이에요."),
        ("submit", "제출할게요."),
    ],
    "parse-html": [
        ("problem", "자, 네 단계를 한 번에 해요. soup를 만들고, #prices li를 하나씩 돌면서 코드, 이름, 가격을 담은 딕셔너리를 rows에 모은 뒤 rows로 df를 만들어요."),
        ("starter", "준비 코드가 html 글자까지 읽어 뒀어요. 이번엔 soup부터 여러분이 만들어요."),
        ("code", "soup=BeautifulSoup(html,'html.parser')\n", "1단계 읽기요. BeautifulSoup에 html 글자와 파서 이름을 넘겨 soup를 만들어요."),
        ("code", "rows=[]\nfor item in soup.select('#prices li'):\n    rows.append({'code':item['data-code'],'name':item.select_one('.name').get_text(strip=True),'price':int(item.select_one('b').get_text(strip=True).replace(',',''))})\n", "2, 3, 4단계가 한 번에요. li마다 딕셔너리 하나. 코드는 item['data-code']로 속성에서, 이름은 .name의 글자, 가격은 b의 글자에서 쉼표를 지우고 int. 그걸 rows에 append해요."),
        ("code", "df=pd.DataFrame(rows)\ndf\n", "딕셔너리 리스트를 DataFrame에 넣으면 표가 돼요. 앞 단원에서 본 그대로죠."),
        ("output", "2행 3열 표가 나왔죠? code A, B, name 가상A, 가상B, price 10000, 20000. 웹 페이지 글자가 숫자 든 표가 됐어요."),
        ("submit", "제출할게요. 세 열의 값을 다 봐요."),
    ],

    # ---- 2장 도전 과제 ----
    "croissant-clean": [
        ("problem", "자, 도전 과제예요. 빵 공장의 8주치 판매 기록 56행인데 판매량이 빈 날이 있어요. 읽기, 결측, 조건 선택, 저장을 한 번에 써요. 다섯 가지 결과 변수를 만들면 돼요."),
        ("hint", "힌트를 보세요. 결측 세기는 isna().sum(), 채우기는 fillna를 새 변수에, 토 또는 일은 isin이 편해요. 저장은 to_csv(index=False)예요."),
        ("starter", "준비 코드가 data/croissant.csv를 sales에 읽어 뒀어요. 그대로 둘게요."),
        ("code", "n_missing = int(sales['판매량'].isna().sum())\n", "1번, 결측 개수요. 판매량 열에 isna().sum()을 하고 int로 감싸요."),
        ("code", "filled = sales.copy()\nfilled['판매량'] = filled['판매량'].fillna(sales['판매량'].median())\n", "2번, 채우기요. 원본을 건드리면 안 되니까 copy로 filled를 만들고, 그 판매량을 중앙값으로 채워요."),
        ("code", "rainy = filled[filled['날씨'] == '비']\nweekend_mean = filled[filled['요일'].isin(['토', '일'])]['판매량'].mean()\n", "3번과 4번, 조건 선택이요. 날씨가 비인 행은 등호 조건으로, 토 또는 일은 isin으로 골라요. 고른 행의 판매량에 mean을 붙이면 주말 평균이에요."),
        ("code", "filled.to_csv('croissant_clean.csv', index=False)\nsaved = pd.read_csv('croissant_clean.csv')\n", "5번, 저장이요. filled를 index=False로 저장하고 다시 읽어 saved에 담아요."),
        ("code", "print(n_missing, len(rainy), round(weekend_mean, 1), saved.shape)\n", "네 값을 한 줄에 출력해서 확인해요."),
        ("output", "2 15 557.6 (56, 5)가 나왔죠? 결측 2개, 비 온 날 15일, 주말 평균 557.6개, 저장한 표 56행 5열이에요."),
        ("submit", "제출할게요. 검사는 원본 sales가 그대로인지, filled에 빈 칸이 없는지도 봐요."),
    ],
}
