"""해설 모드 scripts for chapter 4 (visualization): what the tutor says and types for each concept
and coding problem of the three units plus the chapter challenge, keyed by activity id. Format and
rules: narration.py.

Voice: the instructor's (see .scratch/presenter-decks/spec.md): 해요체 구어, "자," opens a scene,
one or two short sentences per line, says what the student should look at right now. Chart
outputs say what to look at in the picture; printed tables say the numbers.
"""

NARRATION = {
    # ---- Figure·Axes와 막대그래프 ----
    "axes": [
        ("title", "자, 이제 표를 그래프로 바꿔요. 이 개념에서 외울 건 단어 둘이에요."),
        ("앞 단원에서 성별 생존율 표를 만들었죠", "숫자 둘 비교하는 데는 표로 충분해요. 그런데 그룹이 넷, 여섯이 되면 눈이 못 따라가거든요. 그래서 그래프예요."),
        ("제목: 종이와 그래프 영역", "만화를 보세요. fig는 종이 한 장, ax는 그 위의 그래프 영역이에요. 막대도, 축 이름도 전부 ax에 붙여요."),
        ("파이썬에서 그래프를 그리는 도구는", "도구는 matplotlib이에요. Figure가 종이, Axes가 그래프 영역. 우리는 거의 항상 종이 한 장에 그래프 하나만 그려요."),
        ("ax.bar(['A', 'B', 'C'], [30000, 40000, 60000])", "코드 네 줄을 보세요. subplots로 종이와 영역을 만들고, ax.bar로 막대, ax.set으로 제목과 축 이름, plt.show로 띄워요."),
        ("그리는 명령은 종이가 아니라", "그리는 명령은 종이가 아니라 ax에 붙여요. 이 네 줄이 이 챕터 모든 그래프의 뼈대거든요."),
        ("그래프를 그리기 전에 두 가지를 정해 두세요", "그리기 전에 둘을 정해요. y축이 인원인지 퍼센트인지, 그리고 축을 0에서 시작하는지."),
        ("둘째, 축을 어디서 시작하는가", "60부터 자르면 62와 70이 몇 배 차이로 보여요."),
        ("축 이름과 제목은 한글로 적어도 돼요", "제목과 축 이름은 한글로 써도 돼요. 글꼴은 앱이 미리 골라 둬요."),
        ("check", "확인 문항이요. 종이 한 장에 해당하는 이름, 만화에서 봤죠?"),
    ],
    "simple-bar": [
        ("problem", "자, 첫 막대그래프예요. 종목 세 개의 금액을 막대로 그려요. 개념에서 본 네 줄 그대로예요."),
        ("starter", "준비 코드에 names와 amounts 리스트가 있어요. 그대로 둘게요."),
        ("code", "fig, ax = plt.subplots()\n", "먼저 종이 fig와 그래프 영역 ax를 만들어요. 그래프는 항상 이 줄로 시작해요."),
        ("code", "ax.bar(names, amounts)\n", "ax.bar에 이름들과 값들을 넘기면 막대가 그려져요. fig가 아니라 ax에 붙이는 거, 기억하세요."),
        ("code", "ax.set(title='종목별 금액', ylabel='금액')\nplt.show()\n", "ax.set으로 제목과 y축 이름을 한 번에 붙여요. 마지막 plt.show가 다 그렸으니 보여 줘예요."),
        ("run", "실행해 볼게요. 결과 칸에 그림이 떠요."),
        ("output", "막대 세 개가 30000, 40000, 60000 높이로 섰죠? y축 이름 금액도 붙어 있어요."),
        ("submit", "제출하면 검사기가 ax를 읽어서 막대 수와 높이를 확인해요."),
    ],
    "sex-bar": [
        ("problem", "자, 앞 단원의 성별 생존율 표를 그래프로 바꿔요. 비율에 100을 곱해 퍼센트로 그리고, y축은 0에서 100으로 고정해요."),
        ("starter", "준비 코드가 titanic을 읽고 matplotlib과 seaborn을 불러 뒀어요. 그대로 둘게요."),
        ("code", "rates=titanic.groupby('성별')['생존'].mean()\n", "rates는 앞 단원과 같아요. 성별로 묶은 생존의 평균, 그게 생존율이거든요."),
        ("code", "fig,ax=plt.subplots()\nax.bar(rates.index,rates*100)\n", "종이와 영역을 만들고, 막대 이름은 rates.index, 높이는 rates 곱하기 100이에요. 퍼센트로 바꾸는 거죠."),
        ("code", "ax.set(xlabel='성별',ylabel='생존율 (%)',ylim=(0,100),title='성별 생존율')\nplt.show()\n", "ax.set에 x축 이름, y축 이름, 그리고 ylim을 0에서 100으로 넣어요. 그래야 막대 높이가 퍼센트로 읽혀요."),
        ("run", "실행해 볼게요."),
        ("output", "여성 막대가 73 근처, 남성 막대가 19 근처죠? 축이 0에서 100이라 차이가 과장 없이 보여요."),
        ("submit", "제출할게요. 검사기가 축 범위와 막대 높이를 봐요."),
    ],
    "pclass-bar": [
        ("problem", "자, 같은 그래프를 객실 등급으로 그려요. groupby의 열 이름만 바꾸면 되는데, 등급이 숫자라 하나 손봐야 해요."),
        ("starter", "준비 코드는 그대로 둘게요."),
        ("code", "rates = titanic.groupby('객실등급')['생존'].mean()\n", "성별 자리에 객실등급을 넣으면 등급별 생존율이에요."),
        ("code", "fig, ax = plt.subplots()\nax.bar(rates.index.astype(str), rates * 100)\n", "등급 1, 2, 3은 숫자라 x축 간격이 어색해져요. astype(str)로 글자로 바꿔 넘기면 막대가 고르게 서요."),
        ("code", "ax.set(xlabel='객실등급', ylabel='생존율 (%)', ylim=(0, 100), title='Survival by class')\nplt.show()\n", "축 이름과 0에서 100 범위를 붙이고 띄워요."),
        ("run", "실행해 볼게요."),
        ("output", "1등급 62, 2등급 43, 3등급 26 근처로 계단처럼 내려가죠? 등급이 낮아질수록 생존율이 떨어져요."),
        ("submit", "제출할게요."),
    ],

    # ---- 분포와 관계 시각화 ----
    "distribution-types": [
        ("title", "자, 막대그래프 하나로는 답 못 하는 질문이 있어요. 이 개념은 질문별로 그래프를 고르는 법이에요."),
        ("막대그래프는 \"그룹마다 값이 얼마인가\"에 답해요", "막대는 그룹마다 값이 얼마인가에 답해요. 나이가 어떻게 퍼져 있나, 요금과 나이가 같이 움직이나는 다른 질문이거든요."),
        ("제목: 질문이 그래프를 고른다", "만화를 보세요. 어떤 그래프를 그릴까보다 무엇이 궁금한가가 먼저예요."),
        ("제목: 무엇이 궁금한가 → 어떤 그래프", "이 표가 이 단원의 전부예요. 그룹 비교는 막대, 한 열의 퍼짐은 히스토그램, 두 숫자의 관계는 산점도, 시간 변화는 선이에요."),
        ("값이 어떻게 퍼져 있나 → 히스토그램.", "히스토그램은 나이 범위를 같은 폭의 구간 bins로 잘라 구간마다 몇 명인지 세요. 구간 수가 바뀌면 모양도 바뀌니까 보고할 때 구간 수를 같이 적어요. 빈 나이 263명은 먼저 빼요."),
        ("둘이 같이 움직이나 → 산점도.", "산점도는 승객 한 명이 점 하나예요. 가로가 나이, 세로가 요금. 점이 오른쪽 위로 몰리면 같이 움직이는 경향이에요."),
        ("여러 쌍을 한눈에 → 상관계수 히트맵.", "상관계수는 두 열이 얼마나 같이 움직이는지를 -1에서 1 사이 숫자 하나로 줄인 거예요. 열이 여섯이면 6 곱하기 6 표가 나오고, 색으로 칠한 게 히트맵이에요. 대각선은 늘 1이죠."),
        ("sns.histplot(data=known_age, x='나이', bins=20, ax=ax)", "코드를 보세요. 히스토그램은 sns.histplot, 산점도는 ax.scatter, 히트맵은 sns.heatmap이에요. seaborn 함수에는 ax=ax를 꼭 넣어요."),
        ("seaborn은 matplotlib 위에서", "seaborn은 열 이름만으로 그려 주는 도구예요."),
        ("마지막으로, 해석할 때 넘지 말아야 할 선 하나예요", "해석의 선 하나. 요금과 생존의 상관이 양수라는 건 관찰이에요. 요금을 더 내면 산다는 뜻이 아니거든요."),
        ("check", "확인 문항이요. 구간으로 잘라 개수를 세는 그래프, 표에서 봤죠?"),
    ],
    "age-hist": [
        ("problem", "자, 승객 나이가 어떻게 퍼져 있는지 봐요. 빈 나이를 뺀 승객을 known_age에 담고, 구간 20개짜리 히스토그램을 그려요."),
        ("starter", "준비 코드는 그대로 둘게요. seaborn이 sns로 들어와 있어요."),
        ("code", "known_age=titanic.dropna(subset=['나이'])\n", "dropna에 subset으로 나이를 주면 나이가 빈 263명만 빠져요. 1046명이 남죠."),
        ("code", "fig,ax=plt.subplots()\nsns.histplot(data=known_age,x='나이',bins=20,ax=ax)\n", "종이와 영역을 만들고 sns.histplot에 표, 열 이름, bins 20을 넘겨요. ax=ax가 빠지면 다른 곳에 그려서 검사기가 못 찾아요."),
        ("code", "ax.set(xlabel='나이',ylabel='Passenger count',title='Known ages only')\nplt.show()\n", "축 이름과 제목을 붙이고 띄워요."),
        ("run", "실행해 볼게요."),
        ("output", "막대 스무 개가 20대 초반에서 30대 초반 사이에 제일 높죠? 그 네 구간에 500명 넘게 몰려 있어요. 60세 넘어가면 거의 없어요."),
        ("submit", "제출할게요. 검사기는 1046명과 막대 20개를 확인해요."),
    ],
    "fare-scatter": [
        ("problem", "자, 나이와 요금이 같이 움직이는지 봐요. 둘 다 기록된 승객만 known에 담고, 한 명을 점 하나로 찍어요."),
        ("starter", "준비 코드는 그대로 둘게요."),
        ("code", "known = titanic.dropna(subset=['나이', '요금'])\n", "subset에 열 둘을 넣으면 둘 다 값이 있는 행만 남아요. 요금이 빈 한 명이 더 빠져서 1045명이에요."),
        ("code", "fig, ax = plt.subplots()\nax.scatter(known['나이'], known['요금'], alpha=0.4)\n", "ax.scatter에 가로 나이, 세로 요금을 넘겨요. alpha 0.4는 점을 반투명하게 해서 겹친 데가 진하게 보이게 하는 거예요."),
        ("code", "ax.set(xlabel='나이', ylabel='요금', title='Age vs fare')\nplt.show()\n", "축 이름을 붙이고 띄워요."),
        ("run", "실행해 볼게요."),
        ("output", "점 1045개가 아래쪽에 깔려 있죠? 요금 절반이 16 아래라 바닥에 몰리고, 500 넘는 점 몇 개만 위에 떠 있어요. 나이 따라 올라가는 모양은 안 보여요."),
        ("submit", "제출할게요."),
    ],
    "correlation": [
        ("problem", "자, 산점도를 열 쌍마다 그리는 대신 상관계수 표를 만들어 색으로 봐요. 숫자 열 여섯 개예요."),
        ("starter", "준비 코드에 columns 리스트가 있어요. 그대로 둘게요."),
        ("code", "corr=titanic[columns].corr()\n", "여섯 열만 골라서 corr()을 붙이면 6 곱하기 6 상관계수 표가 corr에 들어가요."),
        ("code", "fig,ax=plt.subplots()\nsns.heatmap(corr,annot=True,vmin=-1,vmax=1,center=0,cmap='coolwarm',ax=ax)\n", "sns.heatmap에 corr를 넘겨요. annot은 칸에 숫자 쓰기, vmin과 vmax는 색 범위를 -1에서 1로 고정, coolwarm은 양수가 붉고 음수가 푸른 색이에요."),
        ("code", "plt.show()\n", "띄워요."),
        ("run", "실행해 볼게요."),
        ("output", "대각선이 전부 1로 붉죠? 생존 행을 보세요. 요금이 0.24로 제일 붉고, 객실등급이 -0.31로 제일 푸르러요. 등급 숫자가 커질수록 생존이 줄어든다는 거예요."),
        ("submit", "제출할게요. 검사기는 표 크기와 대각선, 색 범위를 봐요."),
    ],

    # ---- 그래프에서 근거 읽기 ----
    "observations": [
        ("title", "자, 이 단원은 만드는 법이 아니라 읽는 법이에요."),
        ("지금까지 표와 그래프를 여럿 만들었죠", "분석 결과를 말할 때 세 가지를 따로 떼어 적으면 틀린 말을 안 하게 돼요."),
        ("제목: 관찰, 질문, 한계", "만화를 보세요. 표가 말한 건 3등실 남성 493명 중 15%까지예요. 라서는 자료 밖에서 온 거라 다음 질문이나 한계로 적어요."),
        ("첫째, 관찰.", "첫째 관찰, 숫자와 분모로 적어요."),
        ("둘째, 다음 질문.", "둘째 다음 질문, 다른 조건 때문은 아닐까 물어요."),
        ("셋째, 아직 모르는 것.", "셋째 아직 모르는 것, 이 자료에 없는 걸 솔직히 적어요."),
        ("\"등급을 나눠도 성별 차이가 남을까?\"에 답하려면", "등급을 나눠도 차이가 남을까에 답하려면 두 조건으로 묶어요. groupby에 열 이름을 리스트로 넣으면 성별 곱하기 등급, 여섯 그룹이에요. 긴 표를 넓게 펴는 게 unstack이죠."),
        ("grouped = titanic.groupby(['성별', '객실등급'])['생존'].agg(['count', 'mean'])", "코드를 보세요. 두 열로 묶어서 count와 mean을 구하고, mean만 unstack으로 등급을 열로 펼쳐요. 넓은 표에 plot.bar를 붙이면 성별마다 막대 세 개가 묶여요."),
        ("넓은 표를 .plot.bar()에 넘기면", "plot.bar가 묶음 막대를 알아서 그려 주니까 ax.bar를 직접 안 써도 돼요. 분모 count는 넓은 표에 없어요. 긴 표에서 같이 읽어야 해요. 분모가 작은 그룹일수록 비율이 흔들리거든요."),
        ("마지막으로 제목 이야기예요", "제목에는 예쁜 말 대신 무엇을 계산했는지 적어요. 성별·객실등급별 생존율 퍼센트, 이렇게요. 그래프는 혼자 돌아다니거든요."),
        ("check", "확인 문항이요. 등급을 나눠도 차이가 남을까, 이건 셋 중 뭐였죠?"),
    ],
    "embarked-rate": [
        ("problem", "자, groupby를 한 번 더 손에 익혀요. 탑승 항구별로 생존의 count와 mean을 구해 by_port에 담고 마지막 줄에 적어요."),
        ("starter", "준비 코드가 titanic을 읽어 뒀어요. 그대로 둘게요."),
        ("code", "by_port = titanic.groupby('탑승항구')['생존'].agg(['count','mean'])\n", "탑승항구로 묶고 생존 열에 agg로 count와 mean을 한 번에 구해요. 분모와 비율을 같이 보는 거예요."),
        ("code", "by_port\n", "마지막 줄에 이름만 적으면 앱이 표로 보여 줘요."),
        ("run", "실행해 볼게요."),
        ("output", "세 줄이에요. C가 270명 중 56%, Q가 123명 중 36%, S가 914명 중 33%. count를 더하면 1307이죠? 항구가 빈 두 명은 어느 그룹에도 못 들어가요."),
        ("submit", "제출할게요."),
    ],
    "sex-pclass-table": [
        ("problem", "자, 두 조건으로 나눠요. 성별과 객실등급으로 묶은 생존의 count와 mean을 grouped에, mean을 펼친 2행 3열 표를 wide에 담아요."),
        ("starter", "준비 코드는 그대로 둘게요."),
        ("code", "grouped = titanic.groupby(['성별','객실등급'])['생존'].agg(['count','mean'])\n", "groupby에 열 이름을 리스트로 넣는 게 핵심이에요. 성별 둘 곱하기 등급 셋, 여섯 행이 나와요."),
        ("code", "wide = grouped['mean'].unstack('객실등급')\n", "mean 열만 꺼내 unstack에 객실등급을 주면 등급이 열로 옮겨 가요. 값은 그대로고 모양만 바뀌는 거예요."),
        ("code", "wide\n", "마지막 줄에 wide를 적어 표로 봐요."),
        ("run", "실행해 볼게요."),
        ("output", "2행 3열이죠? 여성이 1등급 0.97, 2등급 0.89, 3등급 0.49. 남성은 0.34, 0.15, 0.15예요. 등급을 나눠도 성별 차이가 남아요."),
        ("submit", "제출할게요. 검사기는 grouped 6행과 wide 2행 3열을 봐요."),
    ],
    "combined-groups": [
        ("problem", "자, 방금 만든 넓은 표를 그래프로 바꿔요. 이번엔 wide에 100을 곱해 퍼센트로 두고, plot.bar로 성별마다 등급 막대 세 개를 묶어 그려요."),
        ("starter", "준비 코드는 그대로 둘게요."),
        ("code", "grouped=titanic.groupby(['성별','객실등급'])['생존'].agg(['count','mean'])\n", "grouped는 앞 미션과 같아요. 두 열로 묶어 count와 mean."),
        ("code", "wide=grouped['mean'].unstack('객실등급')*100\n", "unstack으로 펼친 뒤 100을 곱해요. 퍼센트 축이랑 한 세트거든요."),
        ("code", "ax=wide.plot.bar(ylim=(0,100),rot=0)\n", "넓은 표에 plot.bar를 붙이면 그래프 영역 ax를 돌려줘요. ylim은 0에서 100, rot 0은 x축 글자를 세우지 않는 거예요."),
        ("code", "ax.set(ylabel='생존율 (%)',title='성별·객실등급별 생존율 (%)')\nplt.show()\n", "돌려받은 ax에 y축 이름과 제목을 붙여요. 제목에 무엇을 계산했는지 적는 거죠."),
        ("run", "실행해 볼게요."),
        ("output", "막대 여섯 개가 두 묶음이죠? 남성은 34, 15, 15로 전부 낮고, 여성은 97, 89, 49예요. 등급을 나눠도 성별 차이가 남고, 3등급에서 그 차이가 제일 줄어요."),
        ("submit", "제출할게요."),
    ],

    # ---- 챕터 도전 과제 ----
    "two-charts": [
        ("problem", "자, 도전 과제예요. 종이 한 장에 그래프 영역 둘을 나란히 만들고, 왼쪽에 묶음 막대, 오른쪽에 나이 히스토그램을 그려요."),
        ("hint", "힌트를 보세요. 두 그림 다 ax를 지정하는 게 핵심이에요. ax=ax1, ax=ax2가 빠지면 엉뚱한 곳에 그려져요."),
        ("starter", "준비 코드는 그대로 둘게요."),
        ("code", "wide = titanic.groupby(['객실등급', '성별'])['생존'].mean().unstack('성별') * 100\nknown_age = titanic[titanic['나이'].notna()]\n", "재료 둘을 먼저 만들어요. 이번엔 등급이 행, 성별이 열인 wide에 100을 곱하고, 나이가 있는 승객만 known_age에 담아요."),
        ("code", "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11, 4))\n", "subplots에 1, 2를 주면 영역이 가로로 둘이에요. 왼쪽이 ax1, 오른쪽이 ax2. figsize로 종이를 넓게 잡아요."),
        ("code", "wide.plot.bar(ax=ax1, ylim=(0, 100), rot=0)\nax1.set_ylabel('생존율 (%)')\nax1.set_title('등급과 성별에 따른 생존율')\n", "왼쪽이에요. plot.bar에 ax=ax1을 넘겨 그 영역에 그리고, ax1에 y축 이름과 제목을 붙여요."),
        ("code", "sns.histplot(data=known_age, x='나이', bins=20, ax=ax2)\nax2.set_title('나이 분포')\n", "오른쪽이에요. histplot에 ax=ax2, bins 20. 제목도 ax2에 붙여요."),
        ("code", "plt.show()\n", "다 그렸으니 띄워요."),
        ("run", "실행해 볼게요."),
        ("output", "왼쪽에 막대 여섯 개, 등급마다 남성과 여성이 짝이죠? 오른쪽은 막대 스무 개짜리 나이 분포예요. 한 장에 두 질문의 답이 들어갔어요."),
        ("submit", "제출할게요. 검사기는 fig의 영역 둘, 막대 여섯과 스물, 제목 둘을 봐요."),
    ],
}
