"""해설 모드 scripts for chapter 1 (python): what the tutor says and types for each concept and
coding problem, keyed by activity id. Format and rules: narration.py.

Voice: the instructor's (see .scratch/presenter-decks/spec.md): 해요체 구어, "자," opens a scene,
one or two short sentences per line, says what the student should look at right now.
"""

NARRATION = {
    # ---- 내 코드의 첫 실행 ----
    "runtime": [
        ("title", "자, 이 수업이 끝나면 여러분 손에 뭐가 남는지부터 볼게요."),
        ("이 수업이 끝날 때, 여러분의 main.py는", "수업 끝에는 여러분의 main.py가 주가 파일을 읽어서 내일 종가를 맞히고, 얼마나 빗나갔는지까지 숫자로 보고해요. 거기까지 세 토막이에요."),
        ("주가는 예시일 뿐입니다", "주가는 예시예요. 빵 공장이 오늘 몇 개 구울지, 콜센터에 몇 명 앉힐지도 같은 방법이거든요. 아는 숫자로 모르는 숫자를 맞히는 일이죠."),
        ("처음 보는 단어가 쏟아져도 괜찮습니다", "단어가 쏟아져도 괜찮아요. 미션마다 새로 배우는 건 하나예요. 막히면 힌트, 그래도 안 되면 프롬프트 복사로 AI한테 물어보세요."),
        ("앱 사용법은 두 가지만 기억하면 됩니다", "앱은 두 개만 기억하세요. 코드 실행은 연습이라 몇 번 눌러도 되고, 제출은 테스트를 다 통과하면 미션 완료예요. 매 실행은 깨끗한 상태에서 다시 시작해요."),
        ("첫 코드는 한 줄입니다", "첫 코드는 한 줄이에요. print는 괄호 안을 화면에 보여 주는 명령이고, 따옴표는 여기부터 여기까지가 글자라는 표시예요."),
        ("빨간 글씨가 나오면 당황하지 말고", "빨간 글씨가 나오면 맨 마지막 줄을 읽으세요. 파이썬은 원인을 마지막 줄에 적어 두거든요."),
        ("check", "그럼 확인 문항이요. 괄호 안을 화면에 보여 주는 명령, 방금 봤죠?"),
    ],
    "hello": [
        ("problem", "자, 첫 미션은 인사예요. 화면에 Hello, KPC!를 정확히 출력하면 돼요. 대소문자, 쉼표 뒤 공백, 느낌표까지 글자 단위로 비교해요."),
        ("code", "print('Hello, KPC!')\n", "print 괄호 안에 따옴표로 감싼 문장을 넣어요. 따옴표는 짝만 맞으면 작은따옴표든 큰따옴표든 괜찮아요."),
        ("run", "실행해 볼게요. 아래 결과 칸을 보세요."),
        ("output", "Hello, KPC!가 그대로 나왔죠? 빨간 글씨가 나오면 마지막 줄을 읽는다, 기억하세요."),
        ("submit", "제출하면 테스트가 글자 단위로 비교해요. 통과하면 미션 완료예요."),
    ],
    "numbers-text": [
        ("print(30000)과 print('30000')은", "자, print(30000)과 print('30000')은 화면에 똑같이 보여요. 그런데 파이썬한테는 전혀 달라요. 따옴표가 없으면 숫자라 계산이 되고, 있으면 글자라 계산이 안 돼요."),
        ("숫자 가운데 소수점이 없는 것을 정수", "소수점 없는 숫자가 정수 int, 글자 묶음이 문자열 str이에요. 이 구분이 수업 내내 따라다녀요."),
        ("따옴표 하나의 차이", "만화를 보세요. '30000' 곱하기 3을 시키면 파이썬은 글자를 세 번 이어 붙여요. 계산은 안 하죠."),
        ("계산한 값을 나중에 다시 쓰려면 이름표를 붙여 둡니다", "계산한 값을 다시 쓰려면 이름표를 붙여요. price = 10000은 10000을 price라는 이름으로 기억해 둬, 이 뜻이에요. 그게 변수예요."),
        ("=는 \"같다\"가 아니라", "등호는 같다가 아니에요. 오른쪽 값을 왼쪽 이름에 넣어라, 이거예요."),
        ("amount = price * quantity", "코드를 보세요. price와 quantity를 곱해서 amount에 넣고, print로 꺼내 봐요. 쉼표로 여러 값을 넣으면 한 줄에 띄워서 보여 줘요."),
        ("글자와 값을 한 문장으로 섞고 싶을 때는", "글자와 값을 섞고 싶으면 따옴표 앞에 f를 붙이고, 값 자리를 중괄호로 표시해요. 금액: 30000원, 이렇게 나와요."),
        ("check", "확인 문항이요. 따옴표 없는 10000, 소수점 없는 숫자의 자료형 이름이에요."),
    ],
    "print-calc": [
        ("problem", "자, 10000원짜리 주식을 3주 샀어요. 금액을 파이썬한테 계산시켜서 30000을 출력하는 거예요."),
        ("code", "print(10000 * 3)\n", "print 괄호 안에 10000 곱하기 3을 그대로 넣어요. 따옴표로 감싸면 안 돼요. 감싸면 계산 안 하고 글자를 그대로 보여 주거든요."),
        ("run", "실행해 볼게요."),
        ("output", "30000이 나왔죠? 파이썬이 먼저 계산하고 결과만 보여 준 거예요."),
    ],
    "variable-print": [
        ("problem", "자, 같은 계산을 이번엔 이름표로 해요. 준비 코드에 price와 quantity가 있어요. 둘을 곱해서 amount에 저장하고 출력하면 돼요."),
        ("starter", "준비 코드 두 줄은 그대로 둘게요. price가 10000, quantity가 3이에요."),
        ("code", "amount = price * quantity\n", "amount = price 곱하기 quantity. 오른쪽을 먼저 계산해서 amount에 넣어요. 30000을 직접 적으면 가격이 바뀔 때 틀리는 코드가 돼요."),
        ("code", "print(amount)\n", "그다음 줄에서 amount를 출력해요. 이름으로 꺼내 쓰는 거죠."),
        ("output", "30000이 나왔어요. 검사는 amount가 price 곱하기 quantity로 계산됐는지도 봐요."),
    ],
    "single-input": [
        ("problem", "자, 이번엔 수량을 코드에 박지 않고 바깥에서 받아요. 준비 코드가 실행 입력 칸의 한 줄을 읽어서 정수 quantity로 만들어 둬요."),
        ("examples", "예제를 보세요. 입력이 3이면 30000, 7이면 70000이 나와야 해요."),
        ("starter", "준비 코드 한 줄, input()으로 한 줄 받아서 int()로 정수로 바꾼 거예요. 그대로 둘게요."),
        ("code", "print(10000 * quantity)\n", "할 일은 한 줄이에요. 10000에 quantity를 곱해서 출력해요. input()은 글자를 돌려주니까 int()가 없으면 곱셈이 안 돼요."),
        ("input", "실행 입력 칸에 3이 들어가 있어요. 이 값으로 실행해요. 7이나 0으로 바꿔 보셔도 돼요."),
        ("output", "30000이 나왔죠? 제출하면 테스트가 여러 입력으로 확인해요."),
    ],
    "read-input": [
        ("input()이 돌려주는 것은 언제나", "자, input()은 언제나 글자 한 줄을 돌려줘요. 3을 넣어도 문자열 '3'이에요. 그래서 int로 바꿔야 계산이 되죠. 앞 미션 준비 코드가 int(input())이었던 이유예요."),
        ("그러면 한 줄에 10000 3처럼 값이 두 개 들어오면", "한 줄에 값이 두 개 들어오면요? 먼저 공백에서 잘라요. '10000 3'.split()은 글자 두 개가 든 리스트를 돌려줘요."),
        ("아직 글자라서 각각 int로 바꿔야 하는데", "잘린 조각은 아직 글자라 각각 int로 바꿔야 해요. 그걸 한 번에 해 주는 게 map(int, ...)이에요."),
        ("제목: map(int, ['10000', '3', '250', '7', '42'])", "그림을 보세요. 왼쪽 글자 하나하나가 오른쪽 숫자로 바뀌어요. '3'이 3으로, '250'이 250으로. 전부에 int를 적용하는 거예요."),
        ("price, quantity = map(int, input().split())", "이 한 줄이 앞으로 입력받는 모든 문제에서 반복돼요. 안쪽부터 읽어요. input()으로 한 줄, split()으로 자르고, map(int)로 전부 정수로, 두 이름에 나눠 담기."),
        ("check", "확인 문항이요. 공백으로 이어진 글자를 두 조각으로 자르는 메서드, 방금 그림 위에 있었죠."),
    ],
    "amount-input": [
        ("problem", "자, 실행 입력 한 줄에 가격과 수량이 공백으로 들어와요. 준비 코드가 두 값을 정수 price, quantity로 나눠 담아 둬요. 가격 곱하기 수량을 출력하면 돼요."),
        ("examples", "입력 10000 3이면 출력 30000이에요."),
        ("starter", "준비 코드가 입력 처리를 다 했어요. map(int, input().split()), 개념에서 본 그 한 줄이죠."),
        ("code", "print(price * quantity)\n", "남은 건 price와 quantity를 곱해서 print에 넣는 것뿐이에요."),
        ("output", "30000이 나왔어요. 입력을 바꾸면 결과도 따라 바뀌어요."),
    ],
    "fstring-report": [
        ("problem", "자, 숫자만 덜렁 나오면 뭔지 알기 어렵잖아요. 같은 계산을 금액: 30000원 형식의 문장으로 출력해요. 콜론 뒤 공백 한 칸, 숫자 바로 뒤에 원."),
        ("starter", "준비 코드가 입력을 받아서 amount까지 계산해 뒀어요. 그대로 둘게요."),
        ("code", "print(f'금액: {amount}원')\n", "따옴표 앞에 f를 붙이고, 값이 들어갈 자리를 중괄호로 표시해요. 중괄호 안의 amount가 실제 값으로 바뀌어요."),
        ("output", "금액: 30000원, 형식 그대로 나왔죠? 띄어쓰기까지 글자 단위로 채점하니까 그대로 맞춰야 해요."),
    ],
    # ---- 변수와 자료구조 ----
    "values": [
        ("title", "자, 이 단원은 값을 담는 그릇이 두 개 늘어요. 리스트와 딕셔너리예요."),
        ("앞 단원에서는 값 하나에 이름 하나를 붙였습니다", "앞 단원엔 값 하나에 이름 하나였죠? 백 일치 가격이면 변수가 백 개예요. 그래서 값 여러 개를 한 줄로 세워 이름 하나에 담아요. 그게 리스트예요."),
        ("제목: 값 백 개에 이름 백 개?", "만화를 보세요. 첫 값은 prices[0], 마지막은 prices[-1]이에요. 자리는 0부터 세거든요."),
        ("prices = [10000, 10200, 10100]", "코드를 보세요. 대괄호 안에 값을 쉼표로 늘어놓으면 리스트예요. len이 개수, sum이 합계, append가 맨 뒤에 하나 붙이기예요."),
        ("리스트의 자리는 0부터 셉니다", "자리는 0부터예요. 첫 값이 prices[0], 둘째가 prices[1]. 셋이 들었는데 prices[3]을 부르면 IndexError가 나요."),
        ('리스트는 "몇 번째"로 값을 찾습니다', "리스트는 몇 번째로 찾아요. 그런데 종목 하나는 이름, 가격, 수량처럼 종류가 다른 값이 한 묶음이죠? 이럴 땐 이름표로 찾는 게 편해요. 그게 딕셔너리예요."),
        ("holding = {'name': '연습A', 'price': 10000, 'quantity': 3}", "중괄호 안에 이름표 콜론 값, 이렇게 쌍으로 적어요. holding['price']라고 부르면 10000이 나와요. 없던 이름표에 넣으면 추가되고요."),
        ("딕셔너리는 중괄호 안에", "이름표를 키라고 불러요. 키는 글자가 정확히 같아야 해요. 대문자 Price로 부르면 KeyError가 나거든요. 리스트는 위치로, 딕셔너리는 키로. 이것만 기억하세요."),
        ("check", "확인 문항이요. 이름표, 그러니까 키로 값을 찾는 그릇, 방금 봤죠?"),
    ],
    "list-index": [
        ("problem", "자, 사흘치 가격이 prices 리스트에 있어요. 첫날을 first, 마지막 날을 last에 담아서 둘을 출력하면 돼요."),
        ("starter", "준비 코드 한 줄, 리스트 prices는 그대로 둘게요."),
        ("code", "first = prices[0]\nlast = prices[-1]\n", "첫 값은 prices[0]이에요. 자리는 0부터 세니까요. 마지막은 뒤에서 첫째, prices[-1]이에요. prices[3]은 없는 자리라 오류예요."),
        ("code", "print(first, last)\n", "쉼표로 두 값을 넣으면 한 줄에 띄워서 보여 줘요."),
        ("output", "10000 10100이 나왔죠? 첫 값과 마지막 값이에요."),
    ],
    "list-len-sum": [
        ("problem", "자, 같은 리스트로 며칠치인지, 다 더하면 얼마인지 구해요. 개수는 count, 합계는 total에 담아 출력하면 돼요."),
        ("starter", "준비 코드의 prices는 그대로 둘게요."),
        ("code", "count = len(prices)\ntotal = sum(prices)\n", "len(prices)가 개수, sum(prices)가 합계예요. 둘 다 리스트를 괄호에 넣기만 하면 돼요."),
        ("code", "print(count, total)\n", "두 값을 한 줄에 출력해요."),
        ("output", "3 30300이 나왔어요. 사흘치고, 합이 30300이죠."),
    ],
    "dict-read": [
        ("problem", "자, 이번엔 딕셔너리예요. holding에서 가격과 수량을 키로 꺼내 곱한 금액을 amount에 담아 출력하면 돼요. 딕셔너리 자체는 안 바꿔요."),
        ("starter", "준비 코드의 holding은 그대로 둘게요. name, price, quantity 세 키가 있어요."),
        ("code", "amount = holding['price'] * holding['quantity']\n", "대괄호 안에 키를 따옴표째 적어요. holding['price']가 10000, holding['quantity']가 3이죠. 따옴표를 빼면 price라는 변수를 찾다가 NameError가 나요."),
        ("code", "print(amount)\n", "amount를 출력해요."),
        ("output", "30000이 나왔죠? 앞 단원에 변수로 했던 계산을 키로 한 거예요."),
    ],
    "holdings-access": [
        ("problem", "자, 둘을 합쳐요. holdings는 종목 딕셔너리 세 개가 든 리스트예요. 두 번째 종목 이름을 second_name, 세 번째 종목 가격을 third_price에 담아 출력하면 돼요."),
        ("starter", "준비 코드의 holdings는 그대로 둘게요. 한 줄이 길지만 딕셔너리 세 개가 든 리스트예요."),
        ("code", "second_name = holdings[1]['name']\n", "대괄호를 두 번 붙여요. holdings[1]이 두 번째 딕셔너리, 거기에 ['name']으로 이름을 꺼내요. 두 번째 자리가 1이에요."),
        ("code", "third_price = holdings[2]['price']\n", "세 번째 종목은 자리 2예요. holdings[2]['price']로 가격을 꺼내요."),
        ("code", "print(second_name, third_price)\n", "두 값을 출력해요."),
        ("output", "B 15000이 나왔죠? 먼저 위치로 딕셔너리를, 다음에 키로 값을 꺼낸 거예요."),
    ],
    "holding": [
        ("problem", "자, 읽기만 했으니 이번엔 고쳐요. holding의 수량을 5로 바꾸고, 바뀐 수량으로 가격 곱하기 수량을 amount라는 새 키에 넣으면 돼요."),
        ("starter", "준비 코드의 holding은 그대로 둘게요. 수량은 지금 3이에요."),
        ("code", "holding['quantity'] = 5\n", "키에 새 값을 넣으면 바뀌어요. 등호 왼쪽에 holding['quantity']를 두는 거죠."),
        ("code", "holding['amount'] = holding['price'] * holding['quantity']\n", "없던 키 amount에 넣으면 추가돼요. 수량을 바꾼 다음에 곱해야 50000이에요. 순서가 바뀌면 30000이 들어가거든요."),
        ("code", "print(holding)\n", "딕셔너리 전체를 출력해서 확인해요."),
        ("output", "quantity가 5, amount가 50000으로 들어갔죠? 키가 네 개로 늘었어요."),
    ],
    "price-average": [
        ("problem", "자, 넷째 날 가격 10300이 들어왔어요. prices 맨 뒤에 추가하고, 개수를 count, 평균을 average에 담아 둘 다 출력하면 돼요."),
        ("starter", "준비 코드의 prices는 사흘치 그대로 둘게요."),
        ("code", "prices.append(10300)\n", "append가 맨 뒤에 값 하나를 붙여요. 이제 넷이에요."),
        ("code", "count = len(prices)\naverage = sum(prices)/count\n", "개수는 len으로요. 평균은 합계 나누기 개수예요. 파이썬 기본에 average 함수는 없어서 sum을 count로 직접 나눠요."),
        ("code", "print(count, average)\n", "둘을 출력해요."),
        ("output", "4 10150.0이 나왔죠? 나눗셈 결과라 소수점이 붙어요. 그래도 10150이면 맞아요."),
    ],
    # ---- 조건·반복과 DataFrame ----
    "flow": [
        ("title", "자, 이 단원은 코드의 흐름을 바꿔요. 조건에 따라 고르는 if, 여러 값에 반복하는 for예요."),
        ("지금까지의 코드는 위에서 아래로 한 번 흘러가면 끝이었습니다", "지금까진 위에서 아래로 한 번 흐르면 끝이었죠? 만 원 이상일 때만, 이게 if예요. 사흘치를 하나씩 다, 이게 for예요."),
        ("제목: 고르기와 반복하기", "만화 세 번째 컷을 보세요. 네 칸 들여쓴 줄만 if에 딸린 일로 알아들어요. 들여쓰기가 문법이거든요."),
        ("if price >= 10000:", "코드를 보세요. if 뒤에 조건, 콜론, 다음 줄은 네 칸 들여서 할 일. 거짓일 때 할 일은 else 아래예요."),
        ("if 뒤에 조건을 쓰고 콜론", "들여쓰기를 빼면 IndentationError예요. 비교 기호도 보세요. 초과는 >, 이상은 >=예요. 10000이 포함되느냐가 달라요."),
        ("prices = [10000, 10200, 9900, 10100]", "이번엔 for예요. for price in prices 콜론, 그 아래 들여쓴 줄이 값마다 한 번씩 돌아요. 네 값이니 네 번이죠."),
        ("리스트의 값을 하나씩 꺼내 price라는 이름에 넣고", "total += price는 total = total + price를 줄인 거예요. 지금까지의 합에 이번 값을 더해 다시 저장해요. total = 0은 반복 전에 한 번만이에요. 안에 두면 매번 0으로 돌아가거든요."),
        ("for 안에 if를 넣을 수도 있습니다", "for 안에 if를 넣으면 if에 속한 줄은 여덟 칸이에요. 들여쓰기 깊이가 누구에게 속한 줄인지를 말해 줘요."),
        ("check", "확인 문항이요. if 아래 줄은 공백 몇 칸이었죠?"),
    ],
    "simple-if": [
        ("problem", "자, 실행 입력에 가격이 한 줄 들어와요. 10000 이상이면 기준 이상, 아니면 기준 미만을 출력하면 돼요."),
        ("examples", "입력 10200이면 기준 이상, 9900이면 기준 미만이에요. 10000은 어느 쪽일까요? 이상이니까 포함이에요."),
        ("starter", "준비 코드가 입력 한 줄을 정수 price로 만들어 둬요. 그대로 둘게요."),
        ("code", "if price >= 10000:\n    print('기준 이상')\n", "if price >= 10000 콜론. 다음 줄은 공백 네 칸 들여서 print예요. 10000도 포함이니까 >가 아니라 >=예요."),
        ("code", "else:\n    print('기준 미만')\n", "else 콜론, 그 아래 똑같이 네 칸 들여서 기준 미만을 출력해요."),
        ("input", "실행 입력 칸에 10200이 들어가 있어요. 9900이나 10000으로 바꿔 보셔도 돼요."),
        ("output", "기준 이상이 나왔죠? 제출하면 세 입력으로 테스트해요. 10000도 기준 이상이어야 해요."),
    ],
    "for-sum": [
        ("problem", "자, 앞 단원엔 sum()이 합계를 내 줬죠? 이번엔 그 일을 직접 해요. prices 값을 for로 하나씩 꺼내 total에 더하고, 끝나면 total을 출력하면 돼요. sum()은 안 써요."),
        ("starter", "준비 코드 두 줄, prices와 total = 0은 그대로 둘게요. total은 반복 전에 한 번만 만들어요."),
        ("code", "for price in prices:\n    total += price\n", "for price in prices 콜론. 들여쓴 줄에서 total += price. 네 번 돌면서 합이 쌓여요."),
        ("code", "print(total)\n", "print는 들여쓰기 없이 반복문 밖이에요. 그래야 마지막에 한 번만 찍혀요."),
        ("output", "40200이 나왔죠? sum(prices)와 같은 값이에요. 안에서 벌어진 일을 직접 짠 거예요."),
    ],
    "above-count": [
        ("problem", "자, 합계를 구하면서 동시에 10000 이상인 날이 며칠인지도 세요. 합계는 total, 개수는 above_count에 담으면 돼요."),
        ("starter", "준비 코드 세 줄은 그대로 둘게요. total과 above_count가 0으로 시작해요."),
        ("code", "for price in prices:\n    total += price\n", "반복문은 앞 미션과 같아요. 매번 total에 더해요."),
        ("code", "    if price >= 10000:\n        above_count += 1\n", "그 아래 네 칸 들여서 if price >= 10000 콜론. if에 속한 줄은 여덟 칸이에요. 조건에 맞을 때만 above_count에 1을 더해요."),
        ("code", "print(total, above_count)\n", "반복이 끝난 뒤 둘을 출력해요."),
        ("output", "40200 3이 나왔죠? 9900 하루만 빠지고 사흘이 기준 이상이에요."),
    ],
    "max-price": [
        ("problem", "자, 가장 비쌌던 날의 가격을 찾아요. max()면 한 줄이지만, 이번엔 반복문과 if로 직접 찾아 highest에 담아요. 첫 값을 일단 최고로 두고, 더 큰 값을 만나면 바꾸는 방식이에요."),
        ("starter", "준비 코드가 highest를 첫 값 10000으로 시작해 둬요. 그대로 둘게요."),
        ("code", "for price in prices:\n    if price > highest:\n        highest = price\n", "값을 하나씩 꺼내서, 지금 highest보다 크면 갈아 끼워요. 같은 값은 바꿀 필요 없으니 >예요. 반복이 끝나면 가장 큰 값이 남아요."),
        ("code", "print(highest)\n", "반복문 밖에서 출력해요."),
        ("output", "10200이 나왔죠? 이 패턴은 도전 과제에서 또 써요."),
    ],
    "croissant-plan": [
        ("problem", "자, 빵 공장이에요. 새벽마다 크루아상을 몇 개 구울지 정해요. 사흘 판매량 sold로 합계 total, 평균 average, 평균의 1.1배를 반올림한 plan을 만들고 오늘 생산 계획: 460개 형식으로 출력하면 돼요."),
        ("starter", "준비 코드 두 줄, sold와 total = 0은 그대로 둘게요."),
        ("code", "for count in sold:\n    total += count\n", "for로 판매량을 하나씩 꺼내 total에 누적해요. sum()은 안 써요."),
        ("code", "average = total / len(sold)\n", "반복이 끝난 뒤 합계를 개수로 나눠요. 418.3쯤 나와요."),
        ("code", "plan = round(average * 1.1)\n", "품절보다 폐기가 싸다고 했죠? 평균의 1.1배를 round로 반올림하면 정수 460이에요."),
        ("code", "print(f'오늘 생산 계획: {plan}개')\n", "f-문자열로 형식을 맞춰요. 중괄호 안 plan이 460으로 바뀌어요."),
        ("output", "오늘 생산 계획: 460개, 그대로 나왔죠? 합계 1255, 평균 418.3에서 나온 숫자예요."),
    ],
    "holdings-amounts": [
        ("problem", "자, 리스트 안이 숫자가 아니라 딕셔너리여도 for는 똑같이 돌아요. holdings 세 종목을 돌면서 가격 곱하기 수량을 각 종목의 amount 키에 넣으면 돼요."),
        ("starter", "준비 코드의 holdings는 그대로 둘게요. 세 종목이에요."),
        ("code", "for holding in holdings:\n    holding['amount'] = holding['price'] * holding['quantity']\n", "for holding in holdings 콜론. holding에 딕셔너리가 하나씩 들어와요. 안에서 새 키 amount에 가격 곱하기 수량을 넣어요. 앞 단원 holding 미션을 세 번 돈 거예요."),
        ("code", "print(holdings)\n", "반복이 끝난 뒤 리스트 전체를 출력해요."),
        ("output", "세 딕셔너리에 amount가 30000, 40000, 60000으로 붙었죠? 합계는 다음 미션이에요."),
    ],
    "holdings-total": [
        ("problem", "자, 준비 코드엔 금액이 이미 들어 있어요. 세 종목의 amount를 다 더해 total_amount에 담아 출력하면 돼요. for-sum과 같은 모양이에요."),
        ("starter", "준비 코드의 holdings는 그대로 둘게요. amount 키까지 있어요."),
        ("code", "total_amount = 0\n", "누적할 그릇을 반복 전에 한 번 만들어요."),
        ("code", "for holding in holdings:\n    total_amount += holding['amount']\n", "종목을 하나씩 꺼내 그 amount를 total_amount에 더해요."),
        ("code", "print(total_amount)\n", "반복문 밖에서 출력해요."),
        ("output", "130000이 나왔죠? 이 네 줄이 다음 개념에서 한 줄로 줄어요."),
    ],
    "first-dataframe": [
        ("title", "자, 방금 다룬 딕셔너리 묶음이 사실은 표였어요. 여기서 pandas가 나와요."),
        ("방금 다룬 holdings를 종이에 적어 보면 이렇게 됩니다", "holdings를 종이에 적어 보세요. 종목 하나가 한 줄, 이름, 가격, 수량, 금액이 한 칸씩이죠."),
        ("제목: 딕셔너리 묶음이 표가 되기까지", "그림을 보세요. 같은 키를 가진 딕셔너리를 줄줄이 세우면 그게 표예요. 키가 열 이름, 딕셔너리 하나가 한 행. 아래 표가 바로 그거예요. 3행 4열이죠."),
        ("딕셔너리 하나는 표의 한 행이고", "딕셔너리 하나가 한 행, 딕셔너리 리스트가 표 전체예요. 열 더하고 행 고르는 걸 매번 반복문으로 짜면 번거롭죠? 그래서 표 전문 도구 pandas를 써요. 그 표가 DataFrame이에요."),
        ("df = pd.DataFrame(holdings)", "코드를 보세요. pd.DataFrame에 딕셔너리 리스트를 넘기면 바로 표예요. df.shape는 (3, 4), 3행 4열이에요."),
        ("첫 줄 import pandas as pd는", "import pandas as pd는 pandas를 pd라고 짧게 부르겠다는 선언이에요. 표 쓰는 코드 맨 위에 늘 와요. 그리고 마지막 줄에 df만 적으면 앱이 표를 그려 줘요."),
        ("한 열 전체를 더하는 일은 반복문 없이", "한 열 합계는 df['amount'].sum() 한 줄이에요. 아까 네 줄짜리 반복문이 어떻게 줄어드는지 다음 두 미션에서 봐요."),
        ("check", "확인 문항이요. pandas의 표 자료구조 이름이에요. df는 변수 이름일 뿐이죠."),
    ],
    "holdings-frame": [
        ("problem", "자, 금액까지 든 holdings를 DataFrame으로 만들어 df에 담고, 마지막 줄에 df를 적어 표를 띄우면 돼요."),
        ("starter", "준비 코드에 import pandas as pd와 holdings가 있어요. 그대로 둘게요."),
        ("code", "df = pd.DataFrame(holdings)\n", "pd.DataFrame에 딕셔너리 리스트를 넘겨요. 키가 열 이름이 돼요."),
        ("code", "df\n", "마지막 줄에 df만 적어요. print 없이요. 그래야 앱이 표로 그려 줘요."),
        ("output", "표가 나왔죠? 3행 4열, 열 이름이 name, price, quantity, amount 순이에요. 왼쪽 0, 1, 2는 행 번호 인덱스예요."),
    ],
    "frame-column-sum": [
        ("problem", "자, 아까 반복문으로 구한 전체 금액을 이번엔 표로 구해요. df의 amount 열을 골라 .sum()으로 합계를 내서 total_amount에 담아 출력하면 돼요."),
        ("starter", "준비 코드가 df까지 만들어 뒀어요. 그대로 둘게요."),
        ("code", "total_amount = df['amount'].sum()\n", "df['amount']가 한 열이에요. 뒤에 .sum()을 붙이면 그 열의 합계예요. total_amount = 0도, for도 필요 없어요."),
        ("code", "print(total_amount)\n", "출력해요."),
        ("output", "130000, 반복문과 같은 값이죠? 네 줄이 한 줄이 됐어요. 그런데 왜 빠른지는 다음 개념이에요."),
    ],
    "why-fast": [
        ("title", "자, 리스트로도 되는데 왜 pandas냐. 이 질문에 답할게요."),
        ("방금 같은 합계를 반복문으로도, 표로도 구했습니다", "같은 합계를 두 방법으로 구했죠? 답은 둘이에요. 짧고, 빠르다. 짧은 건 봤고, 빠른 이유는 pandas가 NumPy라는 숫자 배열 도구 위에 지어졌기 때문이에요."),
        ("제목: 백만 개 더하기 시합", "만화를 보세요. 반복문은 하나 꺼내고 숫자인지 보고 더하기를 백만 번이에요. 넘파이는 백만 개를 한 덩어리로 받아 C 언어로 한 번에 더해요."),
        ("Python 반복문은 값을 하나 꺼낼 때마다", "반복문은 값마다 이게 숫자인가를 확인해요. 넘파이는 같은 종류 숫자를 메모리 한 덩어리에 두고 C 코드가 한 번에 훑어요. 코어 여러 개가 나눠서 하니까 백만 행이면 수십 배에서 수백 배예요."),
        ("제목: 반복문과 넘파이의 차이", "표로 정리하면 이래요. 하나씩 대 덩어리째, 매번 확인 대 처음 한 번, 코어 하나 대 여러 개."),
        ("values = np.array([10000, 10200, 9900, 10100])", "코드를 보세요. values.sum()은 반복문 없이 40200이고, values * 1.1은 네 값 전부에 한 번에 1.1배예요."),
        ("넘파이의 자리는 생각보다 큽니다", "pandas 표의 한 열이 넘파이 배열이에요. 뒤에서 쓸 scikit-learn도 matplotlib도 넘파이 배열을 주고받아요. 직접 import numpy를 칠 일은 거의 없지만 전부 그 위에 서 있어요."),
        ("여기서 옛날이야기 하나", "옛날엔 넘파이 설치에 컴파일이 필요해서 윈도우에서 자주 실패했어요. 그래서 아나콘다가 필수였죠. 지금은 pip install pandas 한 줄이면 끝이에요. 먼저 아나콘다를 깔라는 자료는 그 시절 이야기예요."),
        ('정리하면 "리스트로도 된다"는 말도 맞고', "정리할게요. 값이 네 개면 차이가 없고, 백만 행이면 백 배예요. 다음 미션에서 그 차이를 직접 재요."),
        ("check", "확인 문항이요. pandas가 그 위에 지어진 숫자 배열 도구, 만화에서 시합한 쪽이에요."),
    ],
    "numpy-race": [
        ("problem", "자, 시합이에요. 0부터 999,999까지가 리스트 values와 넘파이 배열 array에 있어요. for로 더한 합계와 시간을 total, loop_seconds에, array.sum() 결과와 시간을 numpy_total, numpy_seconds에 담고 몇 배 빠른지 출력하면 돼요."),
        ("starter", "준비 코드 네 줄, time과 numpy 가져오기, values와 array는 그대로 둘게요."),
        ("code", "start = time.perf_counter()\n", "시간 재기는 시작 시각을 start에 적어 두는 걸로 시작해요. time.perf_counter()가 지금 시각이에요."),
        ("code", "total = 0\nfor value in values:\n    total += value\nloop_seconds = time.perf_counter() - start\n", "반복문으로 백만 번 누적해요. 끝나면 지금 시각에서 start를 빼요. 그게 걸린 초예요."),
        ("code", "start = time.perf_counter()\nnumpy_total = array.sum()\nnumpy_seconds = time.perf_counter() - start\n", "같은 방식으로 array.sum() 한 줄을 감싸요. start를 다시 찍는 거 보이죠?"),
        ("code", "print(f'반복문 {loop_seconds:.4f}초, 넘파이 {numpy_seconds:.4f}초')\nprint(f'넘파이가 {loop_seconds / numpy_seconds:.0f}배 빠르다')\n", "f-문자열에서 콜론 뒤 .4f는 소수 네 자리, .0f는 정수로 반올림이에요. 배수는 반복문 시간 나누기 넘파이 시간이에요."),
        ("output", "두 줄 나왔죠? 반복문은 백분의 몇 초, 넘파이는 만분의 몇 초, 수십 배에서 백 배쯤이에요. 숫자는 컴퓨터마다 달라요. 합계는 둘 다 499,999,500,000이에요."),
    ],
    # ---- 도전 과제 ----
    "week-plan": [
        ("problem", "자, 도전 과제예요. 빵 공장 지난주 요일별 판매량이 sales 딕셔너리에 있어요. 규칙은 판매량의 1.1배를 반올림해 굽기. 1장에서 배운 걸 전부 써서 plans, total_plan, best_day, df 넷을 만들어요."),
        ("hint", "sales.items()로 키와 값을 함께 꺼내요. 최댓값은 앞에서 본 highest 패턴 그대로예요."),
        ("starter", "준비 코드 네 줄은 그대로 둘게요. plans는 빈 리스트, total_plan은 0으로 시작해요."),
        ("code", "best_day = None\nbest_sold = 0\n", "최댓값 찾기용 그릇 둘을 먼저 만들어요. 아직 요일이 없으니 best_day는 None, best_sold는 0이에요."),
        ("code", "for day, sold in sales.items():\n    plan = round(sold * 1.1)\n    plans.append({'요일': day, '판매량': sold, '계획': plan})\n", "sales.items()는 키와 값을 쌍으로 꺼내요. 요일이 day, 판매량이 sold예요. 1.1배를 반올림해 plan에, 세 키짜리 딕셔너리를 plans에 append해요. 이 키가 그대로 열 이름이 돼요."),
        ("code", "    total_plan += plan\n", "계획 수량을 total_plan에 누적해요. sum()은 금지였죠?"),
        ("code", "    if sold > best_sold:\n        best_sold = sold\n        best_day = day\n", "max() 없이 if로요. 지금까지 최고보다 많이 팔렸으면 best_sold와 best_day를 같이 갈아 끼워요. 여덟 칸 들여쓰기 보세요."),
        ("code", "df = pd.DataFrame(plans)\nprint(total_plan, best_day)\ndf\n", "반복이 끝나면 plans로 표를 만들어요. 합계와 최고 요일을 찍고, 마지막 줄 df로 표를 띄워요."),
        ("output", "3735 토가 찍히고 7행 3열 표가 나왔죠? 토요일 610개가 최고, 계획은 671개예요. 변수, 리스트, 딕셔너리, 반복, 조건, 표를 한 번에 쓴 거예요."),
    ],
}
