"""Regenerate assets/fonts/fonts.css from the woff2 files next to it (base64 @font-face rules)."""
import base64
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1] / "assets" / "fonts"
def face(family, file, weight):
    data = base64.b64encode((ROOT / file).read_bytes()).decode()
    return f"@font-face {{ font-family: '{family}'; src: url(data:font/woff2;base64,{data}) format('woff2'); font-weight: {weight}; font-style: normal; font-display: swap; }}
"
css = "/* Bundled fonts: Pretendard (OFL) for text, JetBrains Mono (OFL) for code. Generated by tools/build-fonts.py. */
"
css += face("Pretendard", "PretendardVariable.woff2", "45 920")
css += face("JetBrains Mono", "JetBrainsMono-Regular.woff2", "400")
css += face("JetBrains Mono", "JetBrainsMono-Bold.woff2", "700")
(ROOT / "fonts.css").write_text(css, encoding="utf-8")
print("fonts.css", len(css) // 1024, "KB")
